# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g8Otut4iNkJF-nGAnnRDUERWRtBQw_yp
"""

# ════════════════════════════════════════════════════════════════
# CELL 1 — Setup, Imports, Paths (SERVER VERSION)
# ════════════════════════════════════════════════════════════════

# --- Standard Library Imports ---
import os, sys, json, math, time, gc, warnings, unicodedata, re, functools
import urllib.parse, logging, hashlib, uuid, pickle, copy, shutil, random
import sqlite3
from datetime import date
from collections import Counter, defaultdict
from dataclasses import dataclass, field
from typing import Dict, List, Set, Tuple, Optional, FrozenSet, NamedTuple, Any
from enum import Enum
from io import BytesIO
from urllib.parse import urlparse

# --- Scientific / ML ---
import numpy as np
import joblib

# --- PyTorch ---
import torch
import torch.nn as nn
import torch.nn.functional as F_t
from PIL import Image
from torchvision import transforms
from efficientnet_pytorch import EfficientNet

# --- Sklearn ---
from sklearn.isotonic import IsotonicRegression
from sklearn.preprocessing import StandardScaler

# --- Domain Parsing ---
import tldextract

# --- IDNA (Punycode / Homograph) ---
try:
    import idna as idna_lib
    IDNA_AVAILABLE = True
except ImportError:
    IDNA_AVAILABLE = False

# --- Selenium ---
from selenium import webdriver
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.chrome.service import Service as ChromeService
from selenium.webdriver.support.ui import WebDriverWait
from selenium.common.exceptions import (
    TimeoutException, WebDriverException, InvalidArgumentException
)

# --- NLTK (English Dictionary for Engine 1) ---
import nltk
nltk.download('words', quiet=True)
from nltk.corpus import words as nltk_words

warnings.filterwarnings("ignore")


# Device Configuration (Server = CPU only)
DEVICE = torch.device("cpu")
USE_AMP = False


# Reproducibility
SEED = 42
random.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED)


# Server Paths — All Model Files
BASE_DIR = "/opt/fakesitehunter/models/Engine 1/models"

E1_WEIGHTS       = f"{BASE_DIR}/engine1_homograph_v13_5.pth"
E1_TOKENIZER     = f"{BASE_DIR}/tokenizer.json"
E1_CALIBRATOR    = f"{BASE_DIR}/calibrator.pkl"
E1_FEAT_STATS    = f"{BASE_DIR}/feature_stats.npz"
E1_MODEL_CONFIG  = f"{BASE_DIR}/model_config.json"
E1_BRAND_DB      = "/opt/fakesitehunter/models/Engine 1/data/brand_db.json"
E1_ENGLISH_DICT  = "/opt/fakesitehunter/models/Engine 1/data/english_dict.txt"
E1_TRANCO_CSV    = "/opt/fakesitehunter/models/Engine 1/data/tranco_safe_list.csv"

E2_ML_MODEL      = "/opt/fakesitehunter/models/Engine 2/Engine3_ML_Model.pkl"
E2_TRANCO_TXT    = "/opt/fakesitehunter/models/Engine 2/tranco_domains.txt"

E3_CNN_WEIGHTS   = "/opt/fakesitehunter/models/Engine 3/EfficientNet_B0_Phishing.pth"

WEBSITE_DIR      = "/opt/fakesitehunter/website"
SCREENSHOT_PATH  = "/tmp/pipeline_screenshot.png"


# ════════════════════════════════════════════════════════════════
# Stats Database — Shared real stats for ALL users
# ════════════════════════════════════════════════════════════════
STATS_DB_PATH = "/opt/fakesitehunter/stats.db"


def _get_stats_db():
    conn = sqlite3.connect(STATS_DB_PATH)
    conn.row_factory = sqlite3.Row
    return conn


def init_stats_db():
    conn = _get_stats_db()
    conn.executescript("""
        CREATE TABLE IF NOT EXISTS scans (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            url TEXT NOT NULL,
            verdict TEXT NOT NULL,
            engines_used TEXT DEFAULT '',
            scanned_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        );

        CREATE TABLE IF NOT EXISTS site_stats (
            id INTEGER PRIMARY KEY DEFAULT 1,
            total_visitors INTEGER DEFAULT 0,
            last_updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        );

        INSERT OR IGNORE INTO site_stats (id, total_visitors) VALUES (1, 0);

        CREATE INDEX IF NOT EXISTS idx_scans_date ON scans(scanned_at);
        CREATE INDEX IF NOT EXISTS idx_scans_verdict ON scans(verdict);
    """)
    conn.commit()
    conn.close()


def record_scan(url, verdict, engines_used=""):
    try:
        conn = _get_stats_db()
        conn.execute(
            "INSERT INTO scans (url, verdict, engines_used) VALUES (?, ?, ?)",
            (url[:500], verdict, engines_used)
        )
        conn.commit()
        conn.close()
    except Exception:
        pass


def increment_visitors():
    try:
        conn = _get_stats_db()
        conn.execute(
            "UPDATE site_stats SET total_visitors = total_visitors + 1, "
            "last_updated = CURRENT_TIMESTAMP WHERE id = 1"
        )
        conn.commit()
        conn.close()
    except Exception:
        pass


def get_stats():
    try:
        conn = _get_stats_db()

        total = conn.execute(
            "SELECT COUNT(*) as c FROM scans"
        ).fetchone()["c"]

        today_str = date.today().isoformat()
        today = conn.execute(
            "SELECT COUNT(*) as c FROM scans WHERE DATE(scanned_at) = ?",
            (today_str,)
        ).fetchone()["c"]

        threats = conn.execute(
            "SELECT COUNT(*) as c FROM scans "
            "WHERE verdict IN ('PHISHING', 'SUSPICIOUS')"
        ).fetchone()["c"]

        visitors = conn.execute(
            "SELECT total_visitors FROM site_stats WHERE id = 1"
        ).fetchone()["total_visitors"]

        conn.close()

        return {
            "total_scans": total,
            "today_scans": today,
            "threats_detected": threats,
            "total_visitors": visitors
        }
    except Exception:
        return {
            "total_scans": 0,
            "today_scans": 0,
            "threats_detected": 0,
            "total_visitors": 0
        }


def get_recent_scans(limit=10):
    try:
        conn = _get_stats_db()
        rows = conn.execute(
            "SELECT url, verdict, engines_used, scanned_at FROM scans "
            "ORDER BY scanned_at DESC LIMIT ?",
            (limit,)
        ).fetchall()
        conn.close()

        return [
            {
                "url": row["url"],
                "verdict": row["verdict"],
                "engines_used": row["engines_used"],
                "time": row["scanned_at"]
            }
            for row in rows
        ]
    except Exception:
        return []


# Selenium Driver Factory (Server Chrome)
def create_driver():
    """Create a headless Chrome WebDriver instance."""
    opts = Options()
    opts.add_argument('--headless=new')
    opts.add_argument('--no-sandbox')
    opts.add_argument('--disable-dev-shm-usage')
    opts.add_argument('--disable-gpu')
    opts.add_argument('--window-size=1920,1080')
    opts.add_argument('--ignore-certificate-errors')
    opts.add_argument('--disable-extensions')
    opts.add_argument('--disable-popup-blocking')
    opts.add_argument('--disable-notifications')
    opts.add_argument('--lang=en-US')
    opts.add_argument(
        '--user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) '
        'AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36'
    )
    opts.binary_location = '/usr/bin/google-chrome-stable'
    return webdriver.Chrome(options=opts)


# Pipeline Configuration Constants
ENGINE2_CONFIDENCE_THRESHOLD = 60.0
ENGINE3_UNCERTAIN_LOW  = 50.0
ENGINE3_UNCERTAIN_HIGH = 59.9
WEIGHT_ML_NLP     = 0.60
WEIGHT_SCREENSHOT  = 0.40
PAGE_LOAD_TIMEOUT  = 25
PAGE_WAIT_TIMEOUT  = 15
EXTRA_RENDER_WAIT  = 1.5
# ════════════════════════════════════════════════════════════════
# CELL 2 — Engine 1: Helper Functions & Data Loading (SERVER)
# ════════════════════════════════════════════════════════════════

# Hardened URL Normalization

_FW_MAP: Dict[int,int] = {cp: cp-0xFF00+0x20 for cp in range(0xFF01,0xFF5F)}
_FW_MAP[0x3002] = 0x2E
_FW_TRANS = str.maketrans(_FW_MAP)
_PCT_RE = re.compile(r'%[0-9a-fA-F]{2}')
_CTRL_RE = re.compile(r'[\x00-\x1f\x7f]')

INVISIBLE_CHARS = frozenset({
    '\u200b','\u200c','\u200d','\ufeff','\u200e','\u200f',
    '\u2060','\u2061','\u2062','\u2063','\u2064',
    '\u2066','\u2067','\u2068','\u2069','\ufff9','\ufffa','\ufffb'})
BIDI_CONTROLS = frozenset({'\u202a','\u202b','\u202c','\u202d','\u202e'})

def normalize_url(raw: str) -> str:
    try:
        u = raw.strip()
        if _PCT_RE.search(u):
            u = urllib.parse.unquote(u)
            if _PCT_RE.search(u): u = urllib.parse.unquote(u)
        u = u.translate(_FW_TRANS)
        u = unicodedata.normalize("NFKC", u)
        u = _CTRL_RE.sub('', u)
        ul = u.lower()
        for pfx in ("https://","http://","//"):
            if ul.startswith(pfx): u = u[len(pfx):]; break
        if u.lower().startswith("www."): u = u[4:]
        return u.rstrip("/")
    except Exception:
        return raw.strip().rstrip("/")

def extract_domain_name(url: str) -> str:
    try:
        ext = tldextract.extract(normalize_url(url))
        return ext.domain if ext.domain else normalize_url(url).split(".")[0]
    except Exception:
        n = normalize_url(url); return n.split(".")[0] if "." in n else n

def extract_registrable_domain(url: str) -> str:
    try:
        ext = tldextract.extract(normalize_url(url))
        if ext.domain and ext.suffix: return f"{ext.domain}.{ext.suffix}".lower()
        elif ext.domain: return ext.domain.lower()
    except Exception: pass
    n = normalize_url(url); return (n.split("/")[0] if "/" in n else n).lower()

def _extract_raw_domain_preserving_case(url: str) -> str:
    try:
        u = url.strip()
        if _PCT_RE.search(u):
            u = urllib.parse.unquote(u)
            if _PCT_RE.search(u): u = urllib.parse.unquote(u)
        u = u.translate(_FW_TRANS)
        u = unicodedata.normalize("NFKC", u)
        u = _CTRL_RE.sub('', u)
        ul = u.lower()
        for pfx in ("https://","http://","//"):
            if ul.startswith(pfx): u = u[len(pfx):]; break
        if u.lower().startswith("www."): u = u[4:]
        host = u.rstrip("/").split("/")[0]; parts = host.split(".")
        return parts[0] if len(parts) >= 2 else host
    except Exception:
        return url.strip().split(".")[0] if "." in url else url.strip()

def _extract_tld(url: str) -> str:
    try: return tldextract.extract(normalize_url(url)).suffix.lower()
    except Exception: return ""

def _url_has_non_ascii(url: str) -> bool:
    return any(ord(c) > 127 for c in url)

_FULLWIDTH_SPOOFABLE = frozenset({0xFF0E, 0xFF0D, 0xFF0F, 0xFF1A, 0xFF20, 0xFF3F})

def _has_fullwidth_punctuation(url: str) -> bool:
    return any(ord(c) in _FULLWIDTH_SPOOFABLE for c in url)


# English Dictionary

if os.path.exists(E1_ENGLISH_DICT):
    with open(E1_ENGLISH_DICT, "r", encoding="utf-8") as f:
        ENGLISH_DICT: FrozenSet[str] = frozenset(
            line.strip().lower() for line in f if line.strip()
        )
else:
    _RAW_WORDS: FrozenSet[str] = frozenset(
        w.lower() for w in nltk_words.words() if len(w) >= 3
    )
    _EXTRA = frozenset({
        "blog","app","tech","web","dev","startup","cloud","data","cyber",
        "login","signup","online","email","server","hosting","domain",
        "pixel","widget","podcast","stream","gaming","crypto","token",
        "bitcoin","wallet","fintech","saas","devops","backend","frontend",
        "fullstack","api","sdk","cdn","dns","ssl","vpn","seo","cms",
        "crm","erp","iot","nft","dao","defi","metaverse","blockchain",
        "overclocking","overclock","benchmark","benchmarks",
        "newsletter","newsletters","cornerstone","partnership","partnerships",
        "disclaimer","disclaimers","discernment","recycling","recycle",
        "entrepreneurship","entrepreneur","internship","intern",
        "furnishing","furnishings","furniture","government","governments",
        "clockwork","clearwater","screenplay","bluetooth","craftsman",
        "checkpoint","switchboard","soundtrack","brickwork","accelerate",
        "pawnshop","thunderbird","cornmarket","alternative","alternatives",
        "downstream","infrastructure","afternoon","thunderstorm","moonlight",
        "waterfall","blueprint","windmill","craftwork","patchwork",
        "manuscript","classroom","ornament","journalism","tournament",
        "modern","landscape","marketing","printing","converter",
        "miraclesoflove","fresqueduclimat"})
    ENGLISH_DICT = _RAW_WORDS | _EXTRA

_SUFFIXES = sorted(set([
    "ment","tion","sion","ship","ness","able","ible","ful","less",
    "ous","ive","ing","ings","ments","tions","sions",
    "er","or","ist","ism","ity","ent","ant","al","ly","ed","es",
    "ers","ors","ists","isms","ities","ence","ance","ure","ures",
    "ize","ise","ized","ised","izing","ising","ation","ations",
    "ships","nesses","s"]), key=len, reverse=True)

_LEET_IND = frozenset("0134567890@$!|+")

@functools.lru_cache(maxsize=32768)
def _stem_check(word: str) -> bool:
    if word in ENGLISH_DICT: return True
    for sfx in _SUFFIXES:
        if word.endswith(sfx) and len(word)-len(sfx)>=3:
            stem = word[:-len(sfx)]
            if stem in ENGLISH_DICT: return True
            if stem+"e" in ENGLISH_DICT: return True
            if len(stem)>=4 and stem[-1]==stem[-2] and stem[:-1] in ENGLISH_DICT:
                return True
    return False

def _has_leet_indicators(text: str) -> bool:
    return any(c in _LEET_IND for c in text)

@functools.lru_cache(maxsize=16384)
def is_english_word(domain_name: str) -> bool:
    nm = domain_name.lower().strip()
    if _has_leet_indicators(nm): return False
    if _stem_check(nm): return True
    if len(nm)>=6:
        for i in range(3, len(nm)-2):
            if _stem_check(nm[:i]) and _stem_check(nm[i:]): return True
    return False

_KNOWN_DIGIT_COMPOUNDS: FrozenSet[str] = frozenset({
    "mp3","mp4","3gp","h264","h265","x264","x265",
    "b2b","b2c","c2c","p2p","a2a","d2c",
    "w3","w3c","i18n","l10n","g11n","k8s","o11y",
    "3m","3d","2d","4k","8k","5g","4g","3g","2g","6g",
    "e3","f1","f2","g8","g7","g20","h2o","co2","o2","n2o","h2","o3",
    "t20","t10","24x7","24h",
    "s3","ec2","r2","d2","m2","v2","v3","v4",
    "mp3converter","mp3player","mp4player",
    "3dprinting","3dprint","3dmodel","3dmodels","3dmodelscenery",
    "b2bmarketing","b2bsales","b2bplatform",
    "p2plending","p2pnetwork",
    "4kmonitor","4kvideo","4ktv","5gnetwork","5gtechnology",
    "i18next","k8sdashboard",
    "earn2learn","learn2earn","learn2code","code2learn",
    "click2call","pay2play","play2earn",
    "go2market","back2basics","back2school",
    "wd40","wd40company","7up","7eleven","2checkout","3commas",
    "n2","n3","a1","b1","c1","d1","e1","g1",
    "h1","h2","h3","j1","k1","m1","p1","r1",
    "s1","s2","t1","t2","u1","v1","x1","y1","z1"})

@functools.lru_cache(maxsize=8192)
def is_english_digit_compound(domain_name: str) -> bool:
    nm = domain_name.lower().strip()
    if not any(c.isdigit() for c in nm): return False
    if nm in _KNOWN_DIGIT_COMPOUNDS: return True
    segs: List[str]=[]; cur: List[str]=[]
    for c in nm:
        if c.isdigit():
            if cur: segs.append("".join(cur)); cur=[]
        else: cur.append(c)
    if cur: segs.append("".join(cur))
    valid=[s for s in segs if len(s)>=3]
    if valid and all(_stem_check(s) for s in valid):
        if any(len(s)>=4 for s in valid): return True
    joined="".join(segs)
    if len(joined)>=6 and not _has_leet_indicators(joined):
        for i in range(3,len(joined)-2):
            if _stem_check(joined[:i]) and _stem_check(joined[i:]): return True
    runs: List[str]=[]; r: List[str]=[]
    for c in nm:
        if c.isalpha(): r.append(c)
        else:
            if r: runs.append("".join(r)); r=[]
    if r: runs.append("".join(r))
    long=[x for x in runs if len(x)>=4]
    if long and all(_stem_check(x) for x in long): return True
    return False

def is_english_any(dn: str) -> bool:
    return is_english_word(dn) or is_english_digit_compound(dn)

@functools.lru_cache(maxsize=8192)
def _phrase_segment_check(dl: str) -> bool:
    if _stem_check(dl): return True
    n=len(dl)
    if n<6: return False
    i=0; found=0
    while i<n:
        ok=False
        for end in range(min(n,i+20),i+2,-1):
            if dl[i:end] in ENGLISH_DICT or _stem_check(dl[i:end]):
                found+=1; i=end; ok=True; break
        if not ok: return False
    return found>=2

_SUSPICIOUS_TLDS = frozenset({
    "ru","su","cn","tk","ml","ga","cf","gq","cc","pw","ws","top",
    "xyz","club","click","lat","buzz","icu","surf","monster",
    "rest","shop","site","online","fun","info","bid","win","review",
    "stream","download","racing","party","trade","date","loan",
    "work","science","accountant","faith","cricket","space","live"})

def _is_english_with_guard(domain_name, url):
    dn=domain_name.lower().strip()
    if not is_english_any(dn): return False
    if any(ord(c)>127 for c in dn): return False
    if _url_has_non_ascii(url): return False
    tld=_extract_tld(url).lower()
    has_any_digit=any(c.isdigit() for c in dn)
    if has_any_digit and tld in _SUSPICIOUS_TLDS:
        if dn in _KNOWN_DIGIT_COMPOUNDS: return True
        alpha="".join(c for c in dn if c.isalpha())
        if len(alpha)>=5 and alpha in ENGLISH_DICT: return True
        return False
    if len(dn)<=6 and has_any_digit:
        if dn in _KNOWN_DIGIT_COMPOUNDS: return True
        return is_english_word(dn)
    if _has_leet_indicators(dn) and tld in _SUSPICIOUS_TLDS:
        return False
    if has_any_digit and dn not in _KNOWN_DIGIT_COMPOUNDS:
        digit_ct=sum(1 for c in dn if c.isdigit())
        if digit_ct >= len(dn)*0.4: return False
    return True


# Decode Engine (Leet, Case Confusable, Compression)

LEET_MAP: Dict[str,str] = {
    "0":"o","1":"l","2":"z","3":"e","4":"a","5":"s",
    "6":"b","7":"t","8":"b","9":"g","@":"a","$":"s","!":"i","|":"l","+":"t"}
LEET_MULTI: Dict[str,List[str]] = {
    "1":["l","i"],"0":["o"],"3":["e"],"4":["a"],"5":["s"],"7":["t"],"9":["g"]}
CASE_CONFUSABLE: Dict[str,str] = {"I":"l","O":"o"}
COMPRESS_PAIRS: Dict[str,str] = {"rn":"m","cl":"d","vv":"w"}

MULTI_DECODE_MAX_AMBIG = 5

def _apply_leet_single(t):
    return "".join(LEET_MAP.get(c,c) for c in t.lower())
def _apply_case_confusable(t):
    return "".join(CASE_CONFUSABLE.get(c,c) for c in t)
def _apply_compress(t):
    r=t
    for p,rep in COMPRESS_PAIRS.items(): r=r.replace(p,rep)
    return r

def _generate_multi_variants(text: str) -> Set[str]:
    lower=text.lower()
    ambig=[(i,LEET_MULTI[c]) for i,c in enumerate(lower)
           if c in LEET_MULTI and len(LEET_MULTI[c])>1]
    if not ambig: return set()
    if len(ambig)>MULTI_DECODE_MAX_AMBIG:
        vs=set(); base=list(_apply_leet_single(lower))
        for pos,opts in ambig:
            for o in opts: v=base.copy(); v[pos]=o; vs.add("".join(v))
        return vs
    vs=set(); n=len(ambig)
    for mask in range(1<<n):
        chars=list(lower)
        for bit,(pos,opts) in enumerate(ambig):
            chars[pos]=opts[1] if (mask&(1<<bit)) else opts[0]
        result=[]
        for j,c in enumerate(chars):
            if c==lower[j] and c in LEET_MAP and c not in LEET_MULTI:
                result.append(LEET_MAP[c])
            else: result.append(c)
        vs.add("".join(result))
    return vs

@functools.lru_cache(maxsize=16384)
def full_decode(text: str) -> FrozenSet[str]:
    original=text.lower()
    ca=_apply_case_confusable(text).lower()
    la=_apply_leet_single(text); cl=_apply_leet_single(ca)
    mr=_generate_multi_variants(text); mc=_generate_multi_variants(ca)
    intermediates={ca,la,cl}|mr|mc
    compressed=set()
    for form in intermediates:
        c=_apply_compress(form)
        if c!=form: compressed.add(c)
    compressed.add(_apply_leet_single(_apply_compress(original)))
    all_forms=intermediates|compressed; all_forms.discard(original)
    return frozenset(all_forms)

def count_substitutions(orig,dec):
    if len(orig)==len(dec):
        return sum(1 for a,b in zip(orig.lower(),dec) if a!=b)
    return abs(len(orig)-len(dec))

def _leet_position_entropy(dl: str) -> float:
    pos=[i for i,c in enumerate(dl) if c in LEET_MAP]
    if len(pos)<=1: return 0.0
    n=len(dl)
    if n==0: return 0.0
    bins=[0]*5
    for p in pos: bins[min(int(p/n*5),4)]+=1
    total=sum(bins)
    if total==0: return 0.0
    ent=0.0
    for b in bins:
        if b>0: r=b/total; ent-=r*math.log2(r)
    return ent


# Visual Similarity

VISUAL_PAIR_SIM: Dict[Tuple[str,str],float] = {
    ('0','o'):0.95,('o','0'):0.95,('1','l'):0.95,('l','1'):0.95,
    ('1','i'):0.90,('i','1'):0.90,('3','e'):0.80,('e','3'):0.80,
    ('4','a'):0.70,('a','4'):0.70,('5','s'):0.75,('s','5'):0.75,
    ('7','t'):0.65,('t','7'):0.65,('9','g'):0.60,('g','9'):0.60,
    ('I','l'):0.95,('l','I'):0.95,('O','0'):0.95,('0','O'):0.95,
    ('r','n'):0.90,('c','l'):0.75,('v','v'):0.85}

def compute_visual_features(dn):
    nm=dn.lower()
    if len(nm)<2: return 0.0,0.0,0
    sims=[]
    for i in range(len(nm)-1):
        s=VISUAL_PAIR_SIM.get((nm[i],nm[i+1]),0.0)
        if nm[i] in LEET_MAP:
            s=max(s,VISUAL_PAIR_SIM.get((nm[i],LEET_MAP[nm[i]]),0.0))
        sims.append(s)
    mx=max(sims) if sims else 0.0
    av=sum(sims)/len(sims) if sims else 0.0
    ct=sum(1 for s in sims if s>0.5)
    return mx,av,ct


# IDNA2008 Validation

class IDNAResult(NamedTuple):
    is_valid:bool; failure_reason:str; is_suspicious:bool; ace_form:str

def validate_idna2008(domain: str) -> IDNAResult:
    if not IDNA_AVAILABLE: return IDNAResult(True,"",False,"")
    try:
        normalized=unicodedata.normalize("NFC",domain.lower())
        labels=normalized.split(".")
        ace=[]
        for label in labels:
            if not label: continue
            if all(ord(c)<128 for c in label): ace.append(label); continue
            try:
                enc=idna_lib.encode(label, uts46=False)
                ace.append(enc.decode("ascii").rstrip("."))
            except (idna_lib.core.InvalidCodepoint,
                    idna_lib.core.InvalidCodepointContext) as e:
                return IDNAResult(False,f"Invalid: {str(e)[:80]}",True,"")
            except (idna_lib.core.IDNAError,UnicodeError) as e:
                return IDNAResult(False,f"IDNA fail: {str(e)[:80]}",True,"")
        af=".".join(ace) if ace else ""
        sus=False
        for label in labels:
            if not label: continue
            hl=any(c.isascii() and c.isalpha() for c in label)
            hn=any(ord(c)>=128 and unicodedata.category(c).startswith("L") for c in label)
            if hl and hn: sus=True; break
        return IDNAResult(True,"",sus,af)
    except Exception as e:
        return IDNAResult(False,f"Error: {str(e)[:60]}",True,"")

_IDN_TLDS: FrozenSet[str] = frozenset({
    "xn--p1ai","xn--j1amh","xn--80asehdb","xn--80aswg","xn--d1acj3b",
    "xn--fiqs8s","xn--fiqz9s","xn--j6w193g","xn--kprw13d","xn--kpry57d",
    "xn--lgbbat1ad8j","xn--mgba3a4f16a","xn--mgbaam7a8h",
    "xn--mgbai9azgqp6j","xn--mgberp4a5d4ar","xn--mgbtx2b",
    "xn--mgbx4cd0ab","xn--mix891f","xn--node","xn--o3cw4h",
    "xn--ogbpf8fl","xn--s9brj9c","xn--wgbh1c","xn--wgbl6a",
    "xn--xkc2al3hye2a","xn--y9a3aq","xn--yfro4i67o",
    "xn--3e0b707e","xn--45brj9c","xn--h2brj9c",
    "se","no","dk","fi","de","at","ch","pl","cz",
    "ru","ua","by","cn","jp","kr","tw","hk","th",
    "il","ae","sa","eg","tr","gr","bg","rs","hr","si",
    "is","ee","lv","lt"})

def is_allowed_idn(domain,tld,tranco):
    try:
        reg=domain.lower()
        if reg in tranco: return True
        tl=tld.lower().strip(".")
        if tl in _IDN_TLDS:
            ir=validate_idna2008(domain)
            if ir.is_valid and not ir.is_suspicious: return True
        return False
    except Exception: return False


# Unicode-to-Latin Decode Map

def _build_unicode_latin_map():
    m = {}
    cyr = [('а','a'),('е','e'),('о','o'),('р','p'),('с','c'),('у','y'),
        ('х','x'),('і','i'),('ј','j'),('ѕ','s'),('ԁ','d'),('ԛ','q'),('ԝ','w'),
        ('ɑ','a'),('ɡ','g'),('ɩ','i'),('ɪ','i'),('ӏ','l'),
        ('б','b'),('в','v'),('г','g'),('д','d'),('ж','zh'),('з','z'),
        ('и','i'),('й','y'),('к','k'),('л','l'),('м','m'),('н','n'),
        ('п','p'),('т','t'),('ф','f'),('ц','c'),('ч','ch'),('ш','sh'),
        ('щ','sh'),('ъ',''),('ы','y'),('ь',''),('э','e'),('ю','yu'),('я','ya'),
        ('ё','e'),('ї','i'),('є','e'),('ғ','g'),('қ','k'),('ң','n'),
        ('ү','u'),('ұ','u'),('һ','h'),('ә','a'),('ө','o'),
        ('А','A'),('В','B'),('С','C'),('Е','E'),('Н','H'),('І','I'),('Ј','J'),
        ('К','K'),('М','M'),('О','O'),('Р','P'),('Т','T'),('Х','X'),
        ('Ё','E'),('Ї','I'),('Є','E'),('Ғ','G'),('Қ','K'),('Ұ','U'),
        ('Ә','A'),('Ө','O'),('Ү','U'),('Һ','H')]
    grk = [('α','a'),('β','b'),('γ','g'),('δ','d'),('ε','e'),('ζ','z'),
        ('η','n'),('θ','th'),('ι','i'),('κ','k'),('λ','l'),('μ','m'),
        ('ν','v'),('ξ','x'),('ο','o'),('π','p'),('ρ','p'),('σ','s'),('ς','s'),
        ('τ','t'),('υ','u'),('φ','f'),('χ','x'),('ψ','ps'),('ω','w'),
        ('Α','A'),('Β','B'),('Γ','G'),('Δ','D'),('Ε','E'),('Ζ','Z'),
        ('Η','H'),('Θ','TH'),('Ι','I'),('Κ','K'),('Λ','L'),('Μ','M'),
        ('Ν','N'),('Ξ','X'),('Ο','O'),('Π','P'),('Ρ','P'),('Σ','S'),
        ('Τ','T'),('Υ','Y'),('Φ','F'),('Χ','X'),('Ψ','PS'),('Ω','W')]
    arm = [('ա','a'),('բ','b'),('գ','g'),('դ','d'),('ե','e'),('զ','z'),
        ('է','e'),('ը','y'),('թ','t'),('ժ','zh'),('ի','i'),('լ','l'),
        ('խ','kh'),('ծ','ts'),('կ','k'),('հ','h'),('ձ','dz'),('ղ','gh'),
        ('ճ','ch'),('մ','m'),('յ','y'),('ն','n'),('շ','sh'),('ո','o'),
        ('չ','ch'),('պ','p'),('ջ','j'),('ռ','r'),(' delays','s'),('վ','v'),
        ('տ','t'),(' delays','r'),('ւ','u'),('փ','p'),('ք','q'),('օ','o'),('ֆ','f')]
    mth = [('𝐚','a'),('𝐛','b'),('𝐜','c'),('𝐝','d'),('𝐞','e'),('𝐟','f'),
        ('𝐠','g'),('𝐡','h'),('𝐢','i'),('𝐣','j'),('𝐤','k'),('𝐥','l'),('𝐦','m'),
        ('𝐧','n'),('𝐨','o'),('𝐩','p'),('𝐪','q'),('𝐫','r'),('𝐬','s'),('𝐭','t'),
        ('𝐮','u'),('𝐯','v'),('𝐰','w'),('𝐱','x'),('𝐲','y'),('𝐳','z'),
        ('𝑎','a'),('𝑏','b'),('𝑐','c'),('𝑑','d'),('𝑒','e'),('𝑓','f'),
        ('𝑔','g'),('𝑕','h'),('𝑖','i'),('𝑗','j'),('𝑘','k'),('𝑙','l'),('𝑚','m'),
        ('𝑛','n'),('𝑜','o'),('𝑝','p'),('𝑞','q'),('𝑟','r'),('𝑠','s'),('𝑡','t'),
        ('𝑢','u'),('𝑣','v'),('𝑤','w'),('𝑥','x'),('𝑦','y'),('𝑧','z'),
        ('ⅽ','c'),('ⅾ','d'),('ⅼ','l'),('ⅿ','m'),('ⅰ','i')]
    for pairs in [cyr,grk,arm,mth]:
        for u,l in pairs: m[u]=l
    for cp in range(0xFF21,0xFF3B): m[chr(cp)]=chr(cp-0xFF21+ord('A'))
    for cp in range(0xFF41,0xFF5B): m[chr(cp)]=chr(cp-0xFF41+ord('a'))
    for cp in range(0xFF10,0xFF1A): m[chr(cp)]=chr(cp-0xFF10+ord('0'))
    m[chr(0xFF0E)]='.'; m[chr(0xFF0D)]='-'
    return m

_UNICODE_TO_LATIN = _build_unicode_latin_map()

def _decode_unicode_to_ascii(text: str) -> str:
    result = []
    for c in text:
        if c in _UNICODE_TO_LATIN: result.append(_UNICODE_TO_LATIN[c])
        elif ord(c) < 128: result.append(c)
        else:
            decomp = unicodedata.normalize("NFKD", c)
            ap = "".join(ch for ch in decomp if ord(ch) < 128)
            if ap: result.append(ap)
    return "".join(result).lower()

def _decode_punycode_label(label: str) -> str:
    if not label.lower().startswith("xn--"): return label.lower()
    try:
        uf = label.encode("ascii").decode("idna")
        return _decode_unicode_to_ascii(uf)
    except Exception:
        try:
            uf = label[4:].encode("ascii").decode("punycode")
            return _decode_unicode_to_ascii(uf)
        except Exception: return label.lower()


# Brand Database (Trie + Tranco Safe List)

CRITICAL_BRANDS: Dict[str,int] = {
    "google":1,"facebook":2,"apple":3,"microsoft":4,"amazon":5,
    "netflix":6,"paypal":7,"instagram":8,"twitter":9,"linkedin":10,
    "whatsapp":11,"telegram":12,"dropbox":13,"spotify":14,
    "cloudflare":15,"github":16,"zoom":17,"slack":18,"stripe":19,
    "shopify":20,"reddit":21,"yahoo":22,"outlook":23,"hotmail":24,
    "youtube":25,"snapchat":26,"pinterest":27,"tumblr":28,
    "wordpress":29,"adobe":30,"salesforce":31,"oracle":32,
    "mozilla":33,"firefox":34,"chrome":35,"safari":36,
    "samsung":37,"huawei":38,"xiaomi":39,"tiktok":40,
    "ebay":41,"walmart":42,"target":43,"bestbuy":44,
    "chase":45,"wellsfargo":46,"bankofamerica":47,"citibank":48,
    "mastercard":49,"visa":50,"venmo":51,"cashapp":52,
    "coinbase":53,"binance":54,"kraken":55,
    "uber":56,"lyft":57,"airbnb":58,"booking":59,
    "steam":60,"epic":61,"playstation":62,"xbox":63,
    "twitch":64,"discord":65,"signal":66,"protonmail":67,
    "icloud":68,"onedrive":69,"meta":70,
    "windows":71,"office":72,"teams":73,"skype":74,
    "wechat":75,"line":76,"viber":77,
    "baidu":78,"alibaba":79,"tencent":80,
    "mailchimp":81,"workday":82,"wikipedia":83,"clever":84}

BRAND_FLOOR_TIER1 = 0.80
BRAND_FLOOR_TIER2 = 0.65
BRAND_FLOOR_TIER3 = 0.50
BRAND_FLOOR_TIER4 = 0.40
BRAND_FLOOR_LOW_SUB = 0.70
MIN_BRAND_LEN_FOR_FLOOR = 4
MIN_BRAND_PREFIX = 5
MIN_BRAND_DECODE_LEN = 3
PREFIX_RANK_LIMIT = 2000
PREFIX_RATIO_TIER1 = 0.30
PREFIX_RATIO_TIER2 = 0.40
PREFIX_RATIO_DEFAULT = 0.50
TRANCO_TOP_N = 10000

class TrieNode:
    __slots__=('children','brand','rank','tier')
    def __init__(self):
        self.children:Dict[str,'TrieNode']={}; self.brand=None; self.rank=0; self.tier=0

class BrandTrie:
    def __init__(self):
        self.root=TrieNode(); self.exact_brands:Dict[str,Tuple[int,int]]={}
    def insert(self,name,rank):
        tier=1 if rank<=100 else (2 if rank<=1000 else (3 if rank<=5000 else 4))
        self.exact_brands[name]=(rank,tier)
        if len(name)<MIN_BRAND_PREFIX: return
        node=self.root
        for ch in name:
            if ch not in node.children: node.children[ch]=TrieNode()
            node=node.children[ch]
        node.brand=name; node.rank=rank; node.tier=tier
    def lookup_exact(self,name):
        if name in self.exact_brands: r,t=self.exact_brands[name]; return True,r,t
        return False,0,0
    def find_longest_prefix_brand(self,text):
        node=self.root; best=None
        for ch in text:
            if ch not in node.children: break
            node=node.children[ch]
            if node.brand: best=(node.brand,node.rank,node.tier)
        return best

class BrandDatabase:
    def __init__(self):
        self.trie=BrandTrie(); self.all_domains:Set[str]=set(); self.loaded=False
    def load_from_json(self, json_path):
        for name,rank in CRITICAL_BRANDS.items():
            self.trie.insert(name,rank)
        if os.path.exists(json_path):
            with open(json_path,"r",encoding="utf-8") as f:
                data=json.load(f)
            for name,info in data.get("brands",{}).items():
                if name not in CRITICAL_BRANDS:
                    self.trie.insert(name,info.get("rank",9999))
            self.all_domains=set(data.get("all_domains",[]))
        self.loaded=True
        return self
    def is_known_safe(self,url):
        reg=extract_registrable_domain(url)
        if reg in self.all_domains: return True
        return normalize_url(url).lower() in self.all_domains
    def _get_prefix_min_ratio(self,tier):
        if tier==1: return PREFIX_RATIO_TIER1
        if tier==2: return PREFIX_RATIO_TIER2
        return PREFIX_RATIO_DEFAULT
    def _is_valid_brand_match(self,brand,decoded_domain,original_domain,match_type):
        if match_type=="exact_decode" and len(brand)<MIN_BRAND_DECODE_LEN: return False
        if match_type=="prefix":
            ratio=len(brand)/len(decoded_domain) if len(decoded_domain)>0 else 0
            found,rank,tier=self.trie.lookup_exact(brand)
            mr=self._get_prefix_min_ratio(tier) if found else PREFIX_RATIO_DEFAULT
            if ratio<mr: return False
            if found and rank>PREFIX_RANK_LIMIT: return False
            if is_english_any(original_domain): return False
        return True
    def check_impersonation(self,domain):
        nl=extract_domain_name(domain).lower()
        nr=_extract_raw_domain_preserving_case(domain)
        found,rank,tier=self.trie.lookup_exact(nl)
        if found: return nl,True,False,0,tier
        dc=full_decode(nr); dl=full_decode(nl); ad=dc|dl
        for dec in ad:
            found,rank,tier=self.trie.lookup_exact(dec)
            if found:
                if not self._is_valid_brand_match(dec,dec,nl,"exact_decode"): continue
                subs=count_substitutions(nl,dec)
                return dec,False,True,max(subs,1),tier
        if is_english_any(nl): return "",False,False,0,0
        for df in ad:
            result=self.trie.find_longest_prefix_brand(df)
            if result:
                brand,rank,tier=result
                if len(df)>len(brand):
                    if not self._is_valid_brand_match(brand,df,nl,"prefix"): continue
                    op=nl[:len(brand)]
                    subs=count_substitutions(op,brand)
                    if subs>0: return brand,False,True,subs,tier
        return "",False,False,0,0
    def check_impersonation_hyphen(self,url):
        b,ex,im,sc,t=self.check_impersonation(url)
        if ex or im: return b,ex,im,sc,t
        nm=extract_domain_name(url).lower()
        for seg in nm.split("-"):
            if len(seg)<3: continue
            sb,se,si,ss,st=self.check_impersonation(seg+".com")
            if si: return sb,False,True,ss,st
        return "",False,False,0,0

BRAND_DB = BrandDatabase()
BRAND_DB.load_from_json(E1_BRAND_DB)

# Brand visual check against Unicode and Punycode domains
def _check_unicode_brand_visual(url):
    norm=normalize_url(url)
    host=norm.split("/")[0] if "/" in norm else norm
    raw_label=host.split(".")[0] if "." in host else host
    ascii_vis=_decode_unicode_to_ascii(raw_label)
    if not ascii_vis or len(ascii_vis)<3: return "",False,0
    uni_subs=sum(1 for c in raw_label if ord(c)>127)
    found,_,_=BRAND_DB.trie.lookup_exact(ascii_vis)
    if found: return ascii_vis,True,max(uni_subs,1)
    all_dec=full_decode(ascii_vis)|{ascii_vis}
    for dec in all_dec:
        found,_,_=BRAND_DB.trie.lookup_exact(dec)
        if found: return dec,True,max(uni_subs,1)
    for dec in all_dec:
        result=BRAND_DB.trie.find_longest_prefix_brand(dec)
        if result:
            brand,_,_=result
            if len(brand)/len(dec)>=0.3 and len(brand)>=4:
                return brand,True,max(uni_subs,1)
    return "",False,0

def _check_punycode_brand(url):
    norm=normalize_url(url)
    host=norm.split("/")[0] if "/" in norm else norm
    for part in host.split("."):
        if not part.lower().startswith("xn--"): continue
        decoded=_decode_punycode_label(part)
        if not decoded or len(decoded)<3: continue
        found,_,_=BRAND_DB.trie.lookup_exact(decoded)
        if found: return decoded,True,1
        all_dec=full_decode(decoded)|{decoded}
        for dec in all_dec:
            found,_,_=BRAND_DB.trie.lookup_exact(dec)
            if found: return dec,True,1
        for dec in all_dec:
            result=BRAND_DB.trie.find_longest_prefix_brand(dec)
            if result:
                brand,_,_=result
                if len(brand)/len(dec)>=0.3 and len(brand)>=4: return brand,True,1
    return "",False,0


# Ambiguity Scorer

_LD=frozenset("0134579"); _VC=frozenset("01345679")

def _compression_guarded(dl,seq):
    if _phrase_segment_check(dl): return True
    if is_english_word(dl): return True
    idx=dl.find(seq)
    if idx==-1: return False
    for s in range(max(0,idx-6),idx+1):
        for e in range(idx+len(seq),min(len(dl)+1,idx+12)):
            sub=dl[s:e]
            if len(sub)>=4 and sub in ENGLISH_DICT: return True
    return False

def ambiguity_score(url):
    nm=extract_domain_name(url).lower(); nl=len(nm)
    if nl<=4: return 0
    sc=0; used:Set[int]=set()
    for i,c in enumerate(nm):
        if c in _LD and 0<i<nl-1 and nm[i-1].isalpha():
            sc+=1; used.add(i); break
    indep=[]
    for i in range(1,nl):
        a,b=nm[i-1],nm[i]
        if (a.isalpha() and b.isdigit()) or (a.isdigit() and b.isalpha()):
            pos=i if b.isdigit() else i-1
            if pos not in used: indep.append(pos)
    if len(indep)>=2: sc+=1; used.update(indep[:2])
    for sq in ("rn","cl","vv"):
        idx=nm.find(sq)
        if idx==-1: continue
        if _compression_guarded(nm,sq): continue
        if idx not in used and idx+1 not in used:
            sc+=1; used.add(idx); used.add(idx+1); break
    vis=sum(1 for c in nm if c in _VC)
    if nl>=8 and vis>=2 and vis/nl>0.15: sc+=1
    segs=nm.split("-")
    if len(segs)>=2:
        te=0
        for seg in segs:
            for i,c in enumerate(seg):
                if c in _LD:
                    ie=(i>0 and seg[i-1].isalpha()) or (i<len(seg)-1 and seg[i+1].isalpha())
                    if ie: te+=1
        if te>=2: sc+=1
    tr=0; clean=nm.replace("-","")
    for c in reversed(clean):
        if c.isdigit(): tr+=1
        else: break
    if tr>0:
        td=sum(1 for c in clean if c.isdigit())
        if tr==td: sc=max(sc-1,0)
    return sc

# ════════════════════════════════════════════════════════════════
# CELL 3 — Engine 1: Neural Model, Constraint Router & Predictor (SERVER)
# ════════════════════════════════════════════════════════════════

# Feature Registry & Configuration

class F(int, Enum):
    URL_LEN=0;NAME_LEN=1;ENTROPY=2;DIGIT_FRAC=3;SPECIAL_FRAC=4
    UNICODE_FRAC=5;DOT_COUNT=6;HAS_PUNYCODE=7;SCRIPT_COUNT=8
    MIXED_SCRIPT=9;VIS_SCORE=10;VOWEL_RATIO=11;MAX_CONSEC_CONS=12
    LEET_MULTI_RATIO=13;CHAR_SUB_COUNT=14;IS_SHORT_DOMAIN=15
    IS_ENGLISH=16;DIGIT_ALPHA_TRANS=17;DIGITS_INSIDE=18
    VIS_SUB_COUNT=19;VIS_SUB_DENSITY=20;DECODE_VARIANT_CT=21
    LEET_POS_ENTROPY=22;INVISIBLE_COUNT=23;HAS_BIDI=24
    MAX_VISUAL_SIM=25;AVG_VISUAL_SIM=26;VISUAL_SIM_COUNT=27

NUM_FEATURES = 28

class Constraint(str, Enum):
    UNICODE_NON_SAFE="UNICODE_IN_NON_SAFE_DOMAIN"
    BRAND_IMPERSONATION="CONFIRMED_BRAND_IMPERSONATION"
    PUNYCODE_NON_SAFE="PUNYCODE_IN_NON_SAFE_DOMAIN"
    KNOWN_SAFE_DOMAIN="DOMAIN_IN_TRANCO_SAFE_LIST"
    ASCII_ZERO_DAY="ASCII_ZERO_DAY_SUSPECTED"
    ENGLISH_NEGATIVE="ENGLISH_WORD_NEGATIVE_EVIDENCE"
    IDNA_INVALID="IDNA2008_VALIDATION_FAILED"
    LEGITIMATE_IDN="LEGITIMATE_IDN_ALLOWED"


# Feature Extraction

def _entropy(s: str) -> float:
    if not s: return 0.0
    freq = Counter(s); n = len(s)
    return -sum((c / n) * math.log2(c / n) for c in freq.values())

def _digit_alpha_transitions(s: str) -> int:
    ct = 0
    for i in range(1, len(s)):
        a, b = s[i - 1], s[i]
        if (a.isalpha() and b.isdigit()) or (a.isdigit() and b.isalpha()):
            ct += 1
    return ct

def _digits_inside_ratio(s: str) -> float:
    nm = s.split(".")[0] if "." in s else s
    if not nm: return 0.0
    inside = 0
    for i, c in enumerate(nm):
        if c.isdigit():
            la = i > 0 and nm[i - 1].isalpha()
            ra = i < len(nm) - 1 and nm[i + 1].isalpha()
            if la or ra: inside += 1
    return inside / max(len(nm), 1)

def extract_single_features(url: str) -> np.ndarray:
    nm = url.split(".")[0] if "." in url else url
    nm_low = nm.lower()
    url_len = len(url)
    nm_len = len(nm)

    unicode_frac = sum(1 for c in url if ord(c) > 127) / max(url_len, 1)
    digit_frac = sum(1 for c in nm if c.isdigit()) / max(nm_len, 1)
    special_frac = sum(1 for c in url if c in "-_~!@#$%^&*()+=|") / max(url_len, 1)

    scripts: Set[str] = set()
    has_nonascii_letter = False
    for c in url:
        if ord(c) > 127:
            try: scripts.add(unicodedata.name(c, "").split(" ")[0])
            except Exception: scripts.add("UNK")
            if unicodedata.category(c).startswith("L"):
                has_nonascii_letter = True
        elif c.isalpha():
            scripts.add("LATIN")
    has_latin = any(c.isascii() and c.isalpha() for c in url)

    vis_chars = frozenset("01345679!$@|")
    vis_score = sum(1 for c in nm if c in vis_chars) / max(nm_len, 1)

    vowels = sum(1 for c in nm_low if c in "aeiou")
    consonants = sum(1 for c in nm_low if c.isalpha() and c not in "aeiou")
    max_consec = cur = 0
    for c in nm_low:
        if c.isalpha() and c not in "aeiou":
            cur += 1; max_consec = max(max_consec, cur)
        else:
            cur = 0

    decoded_forms = full_decode(nm_low)
    char_sub_count = 0
    if decoded_forms:
        char_sub_count = min(count_substitutions(nm_low, dec) for dec in decoded_forms)

    dat = _digit_alpha_transitions(nm)
    diw = _digits_inside_ratio(url)

    vsc = sum(1 for c in nm_low if c in LEET_MAP)
    vsd = vsc / max(nm_len, 1)

    invis = sum(1 for c in url if c in INVISIBLE_CHARS)
    bidi = 1.0 if any(c in BIDI_CONTROLS for c in url) else 0.0

    leet_multi_ratio = sum(1 for c in nm_low if c in LEET_MULTI) / max(nm_len, 1)
    english_flag = 1.0 if is_english_any(nm_low) else 0.0
    is_short = 1.0 if nm_len <= 6 else 0.0
    decode_variant_ct = float(len(decoded_forms))
    leet_pos_ent = _leet_position_entropy(nm_low)
    max_vsim, avg_vsim, vsim_count = compute_visual_features(nm_low)

    feat = np.zeros(NUM_FEATURES, dtype=np.float32)
    feat[F.URL_LEN] = url_len
    feat[F.NAME_LEN] = nm_len
    feat[F.ENTROPY] = _entropy(url)
    feat[F.DIGIT_FRAC] = digit_frac
    feat[F.SPECIAL_FRAC] = special_frac
    feat[F.UNICODE_FRAC] = unicode_frac
    feat[F.DOT_COUNT] = url.count(".")
    feat[F.HAS_PUNYCODE] = 1.0 if "xn--" in url.lower() else 0.0
    feat[F.SCRIPT_COUNT] = len(scripts)
    feat[F.MIXED_SCRIPT] = 1.0 if (has_latin and has_nonascii_letter) else 0.0
    feat[F.VIS_SCORE] = vis_score
    feat[F.VOWEL_RATIO] = vowels / max(consonants, 1)
    feat[F.MAX_CONSEC_CONS] = max_consec
    feat[F.LEET_MULTI_RATIO] = leet_multi_ratio
    feat[F.CHAR_SUB_COUNT] = char_sub_count
    feat[F.IS_SHORT_DOMAIN] = is_short
    feat[F.IS_ENGLISH] = english_flag
    feat[F.DIGIT_ALPHA_TRANS] = dat
    feat[F.DIGITS_INSIDE] = diw
    feat[F.VIS_SUB_COUNT] = vsc
    feat[F.VIS_SUB_DENSITY] = vsd
    feat[F.DECODE_VARIANT_CT] = decode_variant_ct
    feat[F.LEET_POS_ENTROPY] = leet_pos_ent
    feat[F.INVISIBLE_COUNT] = invis
    feat[F.HAS_BIDI] = bidi
    feat[F.MAX_VISUAL_SIM] = max_vsim
    feat[F.AVG_VISUAL_SIM] = avg_vsim
    feat[F.VISUAL_SIM_COUNT] = float(vsim_count)
    return feat


# Tokenizer

class CharTokenizer:
    PAD, UNK, BOS, EOS = 0, 1, 2, 3
    SPECIAL = 4

    def __init__(self, max_len: int = 200, vocab_size: int = 512):
        self.max_len = max_len
        self.vocab_size = vocab_size
        self.c2i: Dict[str, int] = {}
        self.actual_vs: int = self.SPECIAL

    def encode(self, url: str) -> np.ndarray:
        ids = [self.BOS]
        for c in url[:self.max_len - 2]:
            ids.append(self.c2i.get(c, self.UNK))
        ids.append(self.EOS)
        ids += [self.PAD] * (self.max_len - len(ids))
        return np.array(ids[:self.max_len], dtype=np.int64)

    @classmethod
    def load_from_file(cls, path: str) -> 'CharTokenizer':
        with open(path, "r", encoding="utf-8") as f:
            data = json.load(f)
        t = cls(data["max_len"], data["vocab_size"])
        t.c2i = data["c2i"]
        t.actual_vs = data["actual_vs"]
        return t

e1_tokenizer = CharTokenizer.load_from_file(E1_TOKENIZER)
ACTUAL_VOCAB = e1_tokenizer.actual_vs + 4


# Neural Model Architecture

with open(E1_MODEL_CONFIG, "r") as f:
    _e1_config = json.load(f)

_arch = _e1_config.get("architecture", {})
_E1_EMBED_DIM   = _arch.get("embed_dim", 64)
_E1_CNN_FILTERS = _arch.get("cnn_filters", 96)
_E1_GRU_HIDDEN  = _arch.get("gru_hidden", 64)
_E1_TFM_HEADS   = _arch.get("tfm_heads", 4)
_E1_TFM_FF      = _arch.get("tfm_ff", 256)
_E1_TFM_LAYERS  = _arch.get("tfm_layers", 1)
_E1_DROPOUT     = _arch.get("dropout", 0.2)

class HomographNet(nn.Module):
    """CNN(k3+k5) -> BiGRU(64x2) -> Transformer(4h,1L) + Feature FC."""

    def __init__(self, vocab_size: int):
        super().__init__()
        self.embed = nn.Embedding(vocab_size, _E1_EMBED_DIM, padding_idx=0)
        self.embed_drop = nn.Dropout(_E1_DROPOUT)

        self.conv1 = nn.Conv1d(_E1_EMBED_DIM, _E1_CNN_FILTERS, 3, padding=1)
        self.conv2 = nn.Conv1d(_E1_CNN_FILTERS, _E1_CNN_FILTERS, 5, padding=2)
        self.conv_bn = nn.BatchNorm1d(_E1_CNN_FILTERS)
        self.conv_drop = nn.Dropout(_E1_DROPOUT)

        self.gru = nn.GRU(_E1_CNN_FILTERS, _E1_GRU_HIDDEN,
                          batch_first=True, bidirectional=True)
        self.gru_drop = nn.Dropout(_E1_DROPOUT)

        gru_out = _E1_GRU_HIDDEN * 2
        enc_layer = nn.TransformerEncoderLayer(
            d_model=gru_out, nhead=_E1_TFM_HEADS,
            dim_feedforward=_E1_TFM_FF, dropout=_E1_DROPOUT,
            batch_first=True)
        self.transformer = nn.TransformerEncoder(enc_layer, num_layers=_E1_TFM_LAYERS)

        self.feat_fc = nn.Sequential(
            nn.Linear(NUM_FEATURES, 32),
            nn.ReLU(),
            nn.Dropout(_E1_DROPOUT),
        )

        self.head = nn.Sequential(
            nn.Linear(gru_out + 32, 64),
            nn.ReLU(),
            nn.Dropout(_E1_DROPOUT),
            nn.Linear(64, 1),
        )

    def forward(self, tok: torch.Tensor, feat: torch.Tensor) -> torch.Tensor:
        x = self.embed_drop(self.embed(tok))
        x = x.transpose(1, 2)
        x = F_t.relu(self.conv1(x))
        x = F_t.relu(self.conv2(x))
        x = self.conv_drop(self.conv_bn(x))
        x = x.transpose(1, 2)
        x, _ = self.gru(x)
        x = self.gru_drop(x)
        x = self.transformer(x)
        x = x.mean(dim=1) + x.max(dim=1).values

        f = self.feat_fc(feat)
        return self.head(torch.cat([x, f], dim=1)).squeeze(-1)

# Load model weights
e1_checkpoint = torch.load(E1_WEIGHTS, map_location=DEVICE, weights_only=False)
_model_vocab = e1_checkpoint.get("vocab_size", ACTUAL_VOCAB)

e1_model = HomographNet(vocab_size=_model_vocab).to(DEVICE)
e1_model.load_state_dict(e1_checkpoint["model_state_dict"])
e1_model.eval()

# Load calibrator
with open(E1_CALIBRATOR, "rb") as f:
    e1_calibrator = pickle.load(f)

# Load feature normalization stats
_e1_stats = np.load(E1_FEAT_STATS)
e1_feat_mean = _e1_stats["mean"]
e1_feat_std = _e1_stats["std"]


# Constraint Router v13.5

@dataclass
class ConstraintResult:
    triggers:List[str]; brand:str; is_exact:bool; is_impersonation:bool
    sub_count:int; brand_tier:int; unicode_count:int; has_punycode:bool
    is_safe:bool; ascii_score:int; is_english:bool
    route:str; override_confidence:float

def _compute_brand_floor(tier, sub_count, brand_len):
    if brand_len < MIN_BRAND_LEN_FOR_FLOOR: return 0.0
    floors = {1: BRAND_FLOOR_TIER1, 2: BRAND_FLOOR_TIER2,
              3: BRAND_FLOOR_TIER3, 4: BRAND_FLOOR_TIER4}
    fl = floors.get(tier, BRAND_FLOOR_TIER4)
    if sub_count <= 2: fl = max(fl, BRAND_FLOOR_LOW_SUB)
    return fl

HARD_SAFE_MODEL_OVERRIDE_THRESHOLD = 0.90

def compute_constraints(url: str) -> ConstraintResult:
    norm=normalize_url(url);triggers=[];dn=extract_domain_name(url).lower()
    tld=_extract_tld(url);registrable=extract_registrable_domain(url)
    is_safe=BRAND_DB.is_known_safe(url)
    has_uni=any(ord(c)>127 for c in norm)
    uni_ct=sum(1 for c in norm if ord(c)>127)
    has_pc="xn--" in norm.lower()
    has_fw=_has_fullwidth_punctuation(url)
    url_has_uni=_url_has_non_ascii(url)

    if is_safe:
        if url_has_uni:
            orig_uni_ct = sum(1 for c in url if ord(c) > 127)
            triggers.append(Constraint.UNICODE_NON_SAFE.value)
            return ConstraintResult(triggers=triggers,brand="",is_exact=False,
                is_impersonation=False,sub_count=0,brand_tier=0,
                unicode_count=max(orig_uni_ct, 1),
                has_punycode=has_pc,is_safe=False,ascii_score=0,is_english=False,
                route="hard_phish",override_confidence=0.999)
        if has_uni or has_pc:
            br,ex,im,sc,ti=BRAND_DB.check_impersonation_hyphen(url)
            if im and not ex:
                triggers+=[Constraint.UNICODE_NON_SAFE.value,Constraint.BRAND_IMPERSONATION.value]
                return ConstraintResult(triggers=triggers,brand=br,is_exact=False,
                    is_impersonation=True,sub_count=sc,brand_tier=ti,unicode_count=uni_ct,
                    has_punycode=has_pc,is_safe=False,ascii_score=0,is_english=False,
                    route="hard_phish",override_confidence=0.999)
            if has_uni:
                vb,vm,vs=_check_unicode_brand_visual(url)
                if vm:
                    triggers+=[Constraint.UNICODE_NON_SAFE.value,Constraint.BRAND_IMPERSONATION.value]
                    return ConstraintResult(triggers=triggers,brand=vb,is_exact=False,
                        is_impersonation=True,sub_count=vs,brand_tier=1,unicode_count=uni_ct,
                        has_punycode=has_pc,is_safe=False,ascii_score=0,is_english=False,
                        route="hard_phish",override_confidence=0.999)
            if has_pc:
                pb,pm,ps=_check_punycode_brand(url)
                if pm:
                    triggers+=[Constraint.PUNYCODE_NON_SAFE.value,Constraint.BRAND_IMPERSONATION.value]
                    return ConstraintResult(triggers=triggers,brand=pb,is_exact=False,
                        is_impersonation=True,sub_count=ps,brand_tier=1,unicode_count=uni_ct,
                        has_punycode=has_pc,is_safe=False,ascii_score=0,is_english=False,
                        route="hard_phish",override_confidence=0.999)
            if has_uni and uni_ct>0:
                triggers.append(Constraint.UNICODE_NON_SAFE.value)
                return ConstraintResult(triggers=triggers,brand="",is_exact=False,
                    is_impersonation=False,sub_count=0,brand_tier=0,unicode_count=uni_ct,
                    has_punycode=has_pc,is_safe=False,ascii_score=0,is_english=False,
                    route="hard_phish",override_confidence=0.999)
            if has_pc:
                triggers.append(Constraint.PUNYCODE_NON_SAFE.value)
                return ConstraintResult(triggers=triggers,brand="",is_exact=False,
                    is_impersonation=False,sub_count=0,brand_tier=0,unicode_count=uni_ct,
                    has_punycode=True,is_safe=False,ascii_score=0,is_english=False,
                    route="hard_phish",override_confidence=0.999)
        triggers.append(Constraint.KNOWN_SAFE_DOMAIN.value)
        return ConstraintResult(triggers=triggers,brand="",is_exact=False,
            is_impersonation=False,sub_count=0,brand_tier=0,unicode_count=uni_ct,
            has_punycode=has_pc,is_safe=True,ascii_score=0,is_english=False,
            route="hard_safe",override_confidence=0.001)

    if has_uni:
        host=norm.split("/")[0]
        ir=validate_idna2008(host)
        if not ir.is_valid:
            triggers+=[Constraint.UNICODE_NON_SAFE.value,Constraint.IDNA_INVALID.value]
            return ConstraintResult(triggers=triggers,brand="",is_exact=False,
                is_impersonation=False,sub_count=0,brand_tier=0,unicode_count=uni_ct,
                has_punycode=has_pc,is_safe=False,ascii_score=0,is_english=False,
                route="hard_phish",override_confidence=0.999)
        if is_allowed_idn(registrable,tld,BRAND_DB.all_domains):
            br,ex,im,sc,ti=BRAND_DB.check_impersonation_hyphen(url)
            if im and not ex:
                triggers+=[Constraint.UNICODE_NON_SAFE.value,Constraint.BRAND_IMPERSONATION.value]
                return ConstraintResult(triggers=triggers,brand=br,is_exact=False,
                    is_impersonation=True,sub_count=sc,brand_tier=ti,unicode_count=uni_ct,
                    has_punycode=has_pc,is_safe=False,ascii_score=0,is_english=False,
                    route="hard_phish",override_confidence=0.999)
            vb,vm,vs=_check_unicode_brand_visual(url)
            if vm:
                triggers+=[Constraint.UNICODE_NON_SAFE.value,Constraint.BRAND_IMPERSONATION.value]
                return ConstraintResult(triggers=triggers,brand=vb,is_exact=False,
                    is_impersonation=True,sub_count=vs,brand_tier=1,unicode_count=uni_ct,
                    has_punycode=has_pc,is_safe=False,ascii_score=0,is_english=False,
                    route="hard_phish",override_confidence=0.999)
            triggers.append(Constraint.LEGITIMATE_IDN.value)
            return ConstraintResult(triggers=triggers,brand="",is_exact=False,
                is_impersonation=False,sub_count=0,brand_tier=0,unicode_count=uni_ct,
                has_punycode=has_pc,is_safe=True,ascii_score=0,is_english=False,
                route="hard_safe",override_confidence=0.001)
        triggers.append(Constraint.UNICODE_NON_SAFE.value)
        return ConstraintResult(triggers=triggers,brand="",is_exact=False,
            is_impersonation=False,sub_count=0,brand_tier=0,unicode_count=uni_ct,
            has_punycode=has_pc,is_safe=False,ascii_score=0,is_english=False,
            route="hard_phish",override_confidence=0.999)

    if has_pc:
        if is_allowed_idn(registrable,tld,BRAND_DB.all_domains):
            br,ex,im,sc,ti=BRAND_DB.check_impersonation_hyphen(url)
            if im and not ex:
                triggers+=[Constraint.PUNYCODE_NON_SAFE.value,Constraint.BRAND_IMPERSONATION.value]
                return ConstraintResult(triggers=triggers,brand=br,is_exact=False,
                    is_impersonation=True,sub_count=sc,brand_tier=ti,unicode_count=uni_ct,
                    has_punycode=True,is_safe=False,ascii_score=0,is_english=False,
                    route="hard_phish",override_confidence=0.999)
            pb,pm,ps=_check_punycode_brand(url)
            if pm:
                triggers+=[Constraint.PUNYCODE_NON_SAFE.value,Constraint.BRAND_IMPERSONATION.value]
                return ConstraintResult(triggers=triggers,brand=pb,is_exact=False,
                    is_impersonation=True,sub_count=ps,brand_tier=1,unicode_count=uni_ct,
                    has_punycode=True,is_safe=False,ascii_score=0,is_english=False,
                    route="hard_phish",override_confidence=0.999)
            triggers.append(Constraint.LEGITIMATE_IDN.value)
            return ConstraintResult(triggers=triggers,brand="",is_exact=False,
                is_impersonation=False,sub_count=0,brand_tier=0,unicode_count=uni_ct,
                has_punycode=True,is_safe=True,ascii_score=0,is_english=False,
                route="hard_safe",override_confidence=0.001)
        triggers.append(Constraint.PUNYCODE_NON_SAFE.value)
        return ConstraintResult(triggers=triggers,brand="",is_exact=False,
            is_impersonation=False,sub_count=0,brand_tier=0,unicode_count=uni_ct,
            has_punycode=True,is_safe=False,ascii_score=0,is_english=False,
            route="hard_phish",override_confidence=0.999)

    if url_has_uni:
        orig_uni_ct = sum(1 for c in url if ord(c) > 127)
        triggers.append(Constraint.UNICODE_NON_SAFE.value)
        return ConstraintResult(triggers=triggers,brand="",is_exact=False,
            is_impersonation=False,sub_count=0,brand_tier=0,
            unicode_count=max(orig_uni_ct, 1),
            has_punycode=False,is_safe=False,ascii_score=0,is_english=False,
            route="hard_phish",override_confidence=0.999)

    br,ex,im,sc,ti=BRAND_DB.check_impersonation_hyphen(url)
    if im and not ex:
        fl=_compute_brand_floor(ti,sc,len(br))
        if fl>0:
            triggers.append(Constraint.BRAND_IMPERSONATION.value)
            return ConstraintResult(triggers=triggers,brand=br,is_exact=ex,
                is_impersonation=True,sub_count=sc,brand_tier=ti,unicode_count=uni_ct,
                has_punycode=has_pc,is_safe=False,ascii_score=0,is_english=False,
                route="brand_override",override_confidence=fl)

    eng=False
    if not has_uni and not has_pc and not url_has_uni:
        if _is_english_with_guard(dn,url):
            eng=True; triggers.append(Constraint.ENGLISH_NEGATIVE.value)

    asc=ambiguity_score(url)
    if not eng and not ex and asc>=2:
        triggers.append(Constraint.ASCII_ZERO_DAY.value)
        return ConstraintResult(triggers=triggers,brand=br,is_exact=ex,
            is_impersonation=im,sub_count=sc,brand_tier=ti,unicode_count=uni_ct,
            has_punycode=has_pc,is_safe=False,ascii_score=asc,is_english=eng,
            route="ascii_zd",override_confidence=0.0)

    if eng:
        return ConstraintResult(triggers=triggers,brand=br,is_exact=ex,
            is_impersonation=im,sub_count=sc,brand_tier=ti,unicode_count=uni_ct,
            has_punycode=has_pc,is_safe=False,ascii_score=asc,is_english=True,
            route="english",override_confidence=0.0)

    return ConstraintResult(triggers=triggers,brand=br,is_exact=ex,
        is_impersonation=im,sub_count=sc,brand_tier=ti,unicode_count=uni_ct,
        has_punycode=has_pc,is_safe=False,ascii_score=asc,is_english=False,
        route="model",override_confidence=0.0)


# Threshold Function

THRESH_MODEL_ONLY = 0.50
THRESH_ASCII_ZD   = 0.40
THRESH_ENGLISH    = 0.88

def get_threshold_for_route(route, domain_length):
    base = {"ascii_zd": THRESH_ASCII_ZD, "english": THRESH_ENGLISH,
            "model": THRESH_MODEL_ONLY}.get(route, THRESH_MODEL_ONLY)
    if domain_length <= 6: base += 0.05
    elif domain_length >= 15: base -= 0.05
    return max(0.05, min(base, 0.99))


# Homograph Predictor

ENGINE_VERSION = "13.5"

def _error_result(url, reason):
    return {"url": str(url)[:100] if url else "", "is_phish": False,
        "confidence": 0.0, "model_raw": 0.0, "calibrated": 0.0,
        "risk": "UNKNOWN", "brand": "-", "brand_tier": 0,
        "is_exact": False, "is_impersonation": False, "decoded": "-",
        "constraints": [], "constraint_str": "error",
        "route": "error", "decision_path": "error",
        "reason": reason,
        "unicode_count": 0, "has_punycode": False, "is_safe": False,
        "substitutions": 0, "ascii_score": 0, "is_english": False,
        "override_conf": 0.0, "inference_ms": 0.0,
        "engine_version": ENGINE_VERSION}

class HomographPredictor:
    def __init__(self, model, tokenizer, iso_cal, brand_db,
                 feat_mean, feat_std, device, use_amp):
        self.model = model
        self.tokenizer = tokenizer
        self.iso_cal = iso_cal
        self.brand_db = brand_db
        self.feat_mean = feat_mean
        self.feat_std = feat_std
        self.device = device
        self.use_amp = use_amp
        self.model.eval()
        self.version = ENGINE_VERSION

    def _get_model_prob(self, url):
        norm = normalize_url(url)
        tokens = self.tokenizer.encode(norm)
        tok_t = torch.from_numpy(tokens).unsqueeze(0).long().to(self.device)
        feat_raw = extract_single_features(url)
        feat_norm = (feat_raw - self.feat_mean) / self.feat_std
        feat_norm = np.nan_to_num(feat_norm, nan=0.0, posinf=1e6, neginf=-1e6)
        feat_t = torch.from_numpy(feat_norm).unsqueeze(0).float().to(self.device)
        with torch.no_grad():
            logit = self.model(tok_t, feat_t)
            raw_prob = torch.sigmoid(logit).cpu().item()
        cal_prob = float(self.iso_cal.predict([raw_prob])[0])
        return raw_prob, cal_prob

    def predict(self, url):
        try:
            if not url or not isinstance(url, str):
                return _error_result(url, "Invalid input: empty or non-string URL")
            if len(url) > 2048:
                return _error_result(url, f"URL too long ({len(url)} chars, max 2048)")

            t0 = time.time()
            cr = compute_constraints(url)
            dn = extract_domain_name(url).lower()
            dn_len = len(dn)
            raw_prob, cal_prob = self._get_model_prob(url)

            if cr.route == "hard_safe":
                if raw_prob >= HARD_SAFE_MODEL_OVERRIDE_THRESHOLD:
                    final_conf = cal_prob; is_phish = True; dp = "model_override_safe"
                else:
                    final_conf = 0.001; is_phish = False; dp = "hard_safe"
            elif cr.route == "hard_phish":
                final_conf = 0.999; is_phish = True; dp = "hard_phish"
            elif cr.route == "brand_override":
                floor = cr.override_confidence
                final_conf = max(cal_prob, floor); is_phish = True; dp = "brand_override"
            elif cr.route == "ascii_zd":
                final_conf = cal_prob
                threshold = get_threshold_for_route("ascii_zd", dn_len)
                is_phish = final_conf >= threshold; dp = "ascii_zd"
            elif cr.route == "english":
                final_conf = cal_prob
                threshold = get_threshold_for_route("english", dn_len)
                is_phish = final_conf >= threshold; dp = "english"
            else:
                final_conf = cal_prob
                threshold = get_threshold_for_route("model", dn_len)
                is_phish = final_conf >= threshold; dp = "model"

            decoded = cr.brand if cr.brand else ""
            if not decoded:
                dec_forms = full_decode(dn)
                if dec_forms: decoded = sorted(dec_forms)[0]

            if final_conf >= 0.90: risk = "CRITICAL"
            elif final_conf >= 0.75: risk = "HIGH"
            elif final_conf >= 0.50: risk = "MEDIUM"
            elif final_conf >= 0.25: risk = "LOW"
            else: risk = "SAFE"

            reason = self._build_reason(is_phish, cr, dn, decoded, raw_prob, dp)
            cs_str = ", ".join(
                c.split("_")[-1] if "_" in c else c for c in cr.triggers
            ) if cr.triggers else "none"
            latency_ms = (time.time() - t0) * 1000

            return {
                "url": url, "is_phish": is_phish, "confidence": final_conf,
                "model_raw": raw_prob, "calibrated": cal_prob, "risk": risk,
                "brand": cr.brand if cr.brand else "-", "brand_tier": cr.brand_tier,
                "is_exact": cr.is_exact, "is_impersonation": cr.is_impersonation,
                "decoded": decoded if decoded else "-",
                "constraints": cr.triggers, "constraint_str": cs_str,
                "route": cr.route, "decision_path": dp, "reason": reason,
                "unicode_count": cr.unicode_count, "has_punycode": cr.has_punycode,
                "is_safe": cr.is_safe, "substitutions": cr.sub_count,
                "ascii_score": cr.ascii_score, "is_english": cr.is_english,
                "override_conf": cr.override_confidence,
                "inference_ms": latency_ms, "engine_version": self.version
            }

        except Exception as e:
            return _error_result(url, f"Processing error: {str(e)}")

    @staticmethod
    def _build_reason(is_phish, cr, nm, decoded, raw_prob, dp=""):
        if not is_phish:
            if Constraint.KNOWN_SAFE_DOMAIN.value in cr.triggers:
                return "Domain verified in Tranco safe list."
            if Constraint.LEGITIMATE_IDN.value in cr.triggers:
                return "Legitimate internationalized domain."
            if Constraint.ENGLISH_NEGATIVE.value in cr.triggers:
                return "Recognized as natural English word."
            return "No homograph attack detected."
        parts = []
        if dp == "model_override_safe":
            parts.append("Model overrides safe gate (high-confidence phishing).")
        if Constraint.IDNA_INVALID.value in cr.triggers:
            parts.append("Domain fails IDNA2008.")
        if Constraint.UNICODE_NON_SAFE.value in cr.triggers:
            parts.append(f"Contains {cr.unicode_count} non-ASCII char(s). IDN homoglyph.")
        if Constraint.PUNYCODE_NON_SAFE.value in cr.triggers:
            parts.append("Punycode IDN in non-registered domain.")
        if Constraint.BRAND_IMPERSONATION.value in cr.triggers:
            fl = cr.override_confidence
            parts.append(
                f'"{nm}" impersonates "{cr.brand}" (tier {cr.brand_tier}, floor={fl:.0%}).'
            )
        if Constraint.ASCII_ZERO_DAY.value in cr.triggers:
            parts.append(f"ASCII domain has {cr.ascii_score} ambiguity indicator(s).")
        if not parts:
            if raw_prob >= 0.7: parts.append("Suspicious character pattern detected.")
            elif raw_prob >= 0.5: parts.append("Moderate visual suspicion.")
            else: parts.append("Flagged by calibrated model probability.")
        return " ".join(parts)


# Instantiate Predictor

predictor = HomographPredictor(
    model=e1_model,
    tokenizer=e1_tokenizer,
    iso_cal=e1_calibrator,
    brand_db=BRAND_DB,
    feat_mean=e1_feat_mean,
    feat_std=e1_feat_std,
    device=DEVICE,
    use_amp=USE_AMP
)

# ════════════════════════════════════════════════════════════════
# CELL 4 — Engine 2: ML + NLP (LightGBM + Selenium) (SERVER)
# ════════════════════════════════════════════════════════════════

# Load ML Model

_e2_data = joblib.load(E2_ML_MODEL)

e2_ml_model  = _e2_data['model']
e2_scaler    = _e2_data['scaler']
E2_FEATURES  = _e2_data['features']


# Load Tranco Domains (for Engine 2)

e2_tranco_domains = set()

if os.path.exists(E2_TRANCO_TXT):
    with open(E2_TRANCO_TXT, "r") as f:
        for line in f:
            d = line.strip().lower()
            if d:
                e2_tranco_domains.add(d)

TRANCO_HOSTING_OVERRIDE = [
    'github.io', 'vercel.app', 'netlify.app', 'pages.dev',
    'web.app', 'firebaseapp.com', 'herokuapp.com', 'glitch.me',
    'replit.dev', 'replit.app', 'weebly.com', 'wixsite.com',
    'godaddysites.com', 'carrd.co', 'neocities.org', 'ipfs.io',
    'blogspot.com', 'wordpress.com', 'sites.google.com',
    'webflow.io', 'strikingly.com',
    'r2.dev', 'backblazeb2.com', 'workers.dev',
    'azurewebsites.net', 'amplifyapp.com', 'onrender.com',
]

UNTRUSTED_HOSTING = [
    'webflow.io', 'netlify.app', 'vercel.app',
    'blogspot.com', 'weebly.com', 'github.io',
    'pages.dev', 'web.app', 'firebaseapp.com',
    'glitch.me', 'replit.app', 'replit.dev',
    'godaddysites.com', 'wixsite.com', 'carrd.co',
    'neocities.org', 'ipfs.io', 'wordpress.com',
    'sites.google.com', 'webs.com', 'yolasite.com',
    'jimdo.com', 'strikingly.com',
    'r2.dev', 'backblazeb2.com', 'workers.dev',
    'azurewebsites.net', 'amplifyapp.com', 'onrender.com',
]

FORSALE_INDICATORS = [
    'dynadot.com', 'sedo.com', 'dan.com',
    'afternic.com', 'hugedomains.com',
    'undeveloped.com', 'forsale', 'parked',
]

def e2_is_tranco_domain(url):
    if not e2_tranco_domains:
        return False

    hostname = (urlparse(url).hostname or "").lower()

    for h in TRANCO_HOSTING_OVERRIDE:
        if hostname.endswith(h):
            return False

    brand_fake = re.match(r'^(www\.)?([a-z]+)\.com\.[a-z]{2,3}$', hostname)
    if brand_fake:
        brand_name = brand_fake.group(2)
        real_domain = brand_name + '.com'
        if real_domain in e2_tranco_domains and real_domain != hostname:
            return False

    parts = hostname.split('.')
    if len(parts) >= 3:
        base2 = '.'.join(parts[-2:])
        base3 = '.'.join(parts[-3:]) if len(parts) >= 3 else ""
        for h in TRANCO_HOSTING_OVERRIDE:
            if base2 == h or base3 == h:
                return False

    if hostname in e2_tranco_domains:
        return True
    for i in range(len(parts)):
        domain = '.'.join(parts[i:])
        if domain in e2_tranco_domains:
            return True
    return False


# URL Feature Extraction

def extract_url_features(url):
    features = {}
    parsed = urlparse(url)
    hostname = parsed.hostname or ""
    path = parsed.path or ""
    full_url = url.lower()

    shorteners = ['bit.ly','tinyurl.com','goo.gl','t.co','ow.ly','short.link',
                  'tiny.cc','is.gd','buff.ly','rebrand.ly','cutt.ly','rb.gy']

    features['length_url'] = len(url)
    features['length_hostname'] = len(hostname)
    features['ip'] = 1 if re.match(r'^\d{1,3}(\.\d{1,3}){3}$', hostname) else 0

    for char, name in [('.','nb_dots'),('-','nb_hyphens'),('@','nb_at'),('?','nb_qm'),
                       ('&','nb_and'),('|','nb_or'),('=','nb_eq'),('_','nb_underscore'),
                       ('~','nb_tilde'),('%','nb_percent'),('/','nb_slash'),('*','nb_star'),
                       (':','nb_colon'),(',','nb_comma'),(';','nb_semicolumn'),('$','nb_dollar')]:
        features[name] = url.count(char)

    features['nb_space'] = url.count(' ') + url.count('%20')
    features['nb_www'] = full_url.count('www')
    features['nb_com'] = full_url.count('.com')
    features['nb_dslash'] = url.count('//')
    features['http_in_path'] = 1 if 'http' in path.lower() else 0
    features['https_token'] = 1 if parsed.scheme == 'https' else 0
    features['ratio_digits_url'] = sum(c.isdigit() for c in url) / max(len(url), 1)
    features['ratio_digits_host'] = sum(c.isdigit() for c in hostname) / max(len(hostname), 1)
    features['punycode'] = 1 if 'xn--' in hostname.lower() else 0
    features['port'] = 1 if parsed.port and parsed.port not in [80, 443] else 0

    tld_re = r'\.(com|net|org|gov|edu|io|co)\/'
    features['tld_in_path'] = 1 if re.search(tld_re, path.lower()) else 0

    sub_parts = hostname.split('.')[:-2] if hostname.count('.') >= 2 else []
    subdomain = '.'.join(sub_parts)
    features['tld_in_subdomain'] = 1 if re.search(tld_re, subdomain.lower()) else 0
    features['abnormal_subdomain'] = 1 if len(sub_parts) > 2 else 0
    features['nb_subdomains'] = len(sub_parts)
    features['prefix_suffix'] = 1 if '-' in hostname else 0

    domain_name = hostname.split('.')[0] if hostname else ''
    consonants = sum(1 for c in domain_name.lower() if c in 'bcdfghjklmnpqrstvwxyz')
    vowels_ct = sum(1 for c in domain_name.lower() if c in 'aeiou')
    features['random_domain'] = 1 if consonants / (vowels_ct + 1) > 4 else 0
    features['shortening_service'] = 1 if any(s in hostname.lower() for s in shorteners) else 0

    sus_ext = ['.php','.html','.asp','.aspx','.jsp','.cgi']
    features['path_extension'] = 1 if any(path.lower().endswith(e) for e in sus_ext) else 0
    features['nb_redirection'] = url.count('//')
    features['nb_external_redirection'] = 1 if 'redirect' in full_url or 'redir' in full_url else 0

    sep = re.compile(r'[\-\_\.\/?=&@%\+\|#~,;:!\*\(\)\[\]]')
    words_raw = [w for w in sep.split(url) if w and len(w) > 1]
    if words_raw:
        wl = [len(w) for w in words_raw]
        features['length_words_raw'] = len(words_raw)
        features['shortest_words_raw'] = min(wl)
        features['longest_words_raw'] = max(wl)
    else:
        features['length_words_raw'] = 0
        features['shortest_words_raw'] = 0
        features['longest_words_raw'] = 0

    max_rep, cur_rep = 1, 1
    for i in range(1, len(url)):
        if url[i] == url[i-1]:
            cur_rep += 1; max_rep = max(max_rep, cur_rep)
        else:
            cur_rep = 1
    features['char_repeat'] = max_rep

    for part, prefix in [(hostname, 'host'), (path, 'path')]:
        pw = [w for w in sep.split(part) if w and len(w) > 1]
        if pw:
            pl = [len(w) for w in pw]
            features[f'shortest_word_{prefix}'] = min(pl)
            features[f'longest_word_{prefix}'] = max(pl)
        else:
            features[f'shortest_word_{prefix}'] = 0
            features[f'longest_word_{prefix}'] = 0

    return features


# HTML Feature Extraction (via Selenium)

def extract_html_features(driver):
    features = {}
    try:
        driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
        time.sleep(1)
        driver.execute_script("window.scrollTo(0, 0);")
        time.sleep(0.5)

        data = driver.execute_script("""
            var r={}, d=window.location.hostname;
            var links=document.querySelectorAll('a[href],area[href]');
            var t=links.length, i=0, e=0, n=0;
            links.forEach(function(a){
                var h=(a.getAttribute('href')||'').trim();
                if(h==='#'||h===''||h.startsWith('javascript:')||h==='#!'||h==='#0'||h==='#content'){n++}
                else{try{var u=new URL(h,location.href);
                    if(u.hostname===d||u.hostname.endsWith('.'+d)){i++}else{e++}}catch(x){n++}}
            });
            r.nb_hyperlinks=t; r.ratio_intHyperlinks=t>0?i/t:0;
            r.ratio_extHyperlinks=t>0?e/t:0; r.ratio_nullHyperlinks=t>0?n/t:0;

            var css=document.querySelectorAll('link[rel="stylesheet"]'),ec=0;
            css.forEach(function(c){try{var u=new URL(c.href,location.href);
                if(u.hostname!==d)ec++}catch(x){}});
            r.nb_extCSS=ec;

            var sc=document.querySelectorAll('script'),mr=document.querySelector('meta[http-equiv="refresh"]');
            var ir=0,er=0;
            if(mr){var mc=mr.getAttribute('content')||'';if(mc.includes(d))ir++;else er++}
            sc.forEach(function(s){var c=s.innerText.toLowerCase();
                if(c.includes('window.location')||c.includes('location.href')||c.includes('location.replace')){
                    if(c.includes(d))ir++;else er++}});
            var tr=ir+er;
            r.ratio_intRedirection=tr>0?ir/tr:0; r.ratio_extRedirection=tr>0?er/tr:0;

            var imgs=document.querySelectorAll('img'),ie=0,ee=0,tt=0;
            imgs.forEach(function(img){var s=img.src||'';if(!s||s.startsWith('data:'))return;tt++;
                if(img.complete&&img.naturalWidth===0){try{var u=new URL(s,location.href);
                    if(u.hostname===d)ie++;else ee++}catch(x){}}});
            r.ratio_intErrors=tt>0?ie/tt:0; r.ratio_extErrors=tt>0?ee/tt:0;

            r.login_form=document.querySelector('input[type="password"]')?1:0;

            var fav=document.querySelector('link[rel*="icon"]');
            if(fav&&fav.href){try{var fu=new URL(fav.href,location.href);
                r.external_favicon=fu.hostname!==d?1:0}catch(x){r.external_favicon=0}}
            else{r.external_favicon=0}

            var ml=0;document.querySelectorAll('meta[content]').forEach(function(m){
                var c=m.getAttribute('content')||'';
                if(c.includes('http://')||c.includes('https://'))ml++});
            r.links_in_tags=ml;

            var se=0;document.querySelectorAll('form').forEach(function(f){
                if((f.action||'').includes('mailto:'))se=1});
            r.submit_email=se;

            var med=document.querySelectorAll('img,video,audio,embed,object,source'),im=0,em=0;
            med.forEach(function(m){var s=m.src||m.data||'';if(!s||s.startsWith('data:'))return;
                try{var u=new URL(s,location.href);
                    if(u.hostname===d||u.hostname.endsWith('.'+d))im++;else em++}catch(x){}});
            var tm=im+em; r.ratio_intMedia=tm>0?im/tm:0; r.ratio_extMedia=tm>0?em/tm:0;

            var forms=document.querySelectorAll('form'),sfh=0;
            if(forms.length>0){forms.forEach(function(f){var a=(f.action||'').trim();
                if(!a||a==='about:blank'){sfh=2}else{try{var u=new URL(a,location.href);
                    sfh=u.hostname===d?1:-1}catch(x){sfh=2}}});}
            r.sfh=sfh;

            r.iframe=document.querySelectorAll('iframe,frame').length>0?1:0;
            var hp=0;sc.forEach(function(s){if(s.innerText.toLowerCase().includes('window.open'))hp=1});
            r.popup_window=hp; r.safe_anchor=t>0?n/t:0;
            r.onmouseover=document.querySelectorAll('[onmouseover]').length>0?1:0;

            var b=document.body||document.documentElement,h=document.documentElement,rc=0;
            if(b){var ob=(b.getAttribute('oncontextmenu')||'').toLowerCase();
                var oh=(h.getAttribute('oncontextmenu')||'').toLowerCase();
                if(ob.includes('return false')||oh.includes('return false')||
                   ob.includes('preventdefault')||oh.includes('preventdefault'))rc=1;}
            r.right_clic=rc;

            r.empty_title=(!document.title||document.title.trim()==='')?1:0;
            var tl=(document.title||'').toLowerCase(),df=d.split('.')[0];
            r.domain_in_title=(df.length>2&&tl.includes(df))?1:0;

            var bt=b?(b.innerText||'').toLowerCase():'';
            var hc=bt.includes('\\u00a9')||bt.includes('copyright'),dc=false;
            if(hc&&df.length>2){bt.split('\\n').forEach(function(l){
                if((l.includes('\\u00a9')||l.includes('copyright'))&&l.includes(df))dc=true})}
            r.domain_with_copyright=dc?1:0;
            return r;
        """)
        features = data
    except Exception:
        for f_name in ['nb_hyperlinks','ratio_intHyperlinks','ratio_extHyperlinks',
                   'ratio_nullHyperlinks','nb_extCSS','ratio_intRedirection',
                   'ratio_extRedirection','ratio_intErrors','ratio_extErrors',
                   'login_form','external_favicon','links_in_tags','submit_email',
                   'ratio_intMedia','ratio_extMedia','sfh','iframe','popup_window',
                   'safe_anchor','onmouseover','right_clic','empty_title',
                   'domain_in_title','domain_with_copyright']:
            features[f_name] = 0
    return features

def extract_all_features(driver, url):
    final_url = driver.current_url
    return {**extract_url_features(final_url), **extract_html_features(driver)}

def features_to_array(fd):
    return np.array([[fd.get(f, 0) for f in E2_FEATURES]])


# NLP Analysis

def nlp_analysis(driver, url):
    score = 0
    findings = []
    current_domain = urlparse(url).netloc.lower()
    hostname = urlparse(url).hostname or ""

    try:
        page_text = driver.execute_script("""
            var b=document.body;if(!b)return '';
            return(b.innerText||b.textContent||'').substring(0,5000);""")
        page_text = page_text.lower().strip() if page_text else ''
    except Exception:
        page_text = ''

    try:
        page_title = (driver.title or "").lower().strip()
    except Exception:
        page_title = ''

    if len(page_title) < 2 and len(page_text) < 5:
        return score, findings

    brands = {
        'paypal':['paypal.com'],'google':['google.com','gmail.com','googleapis.com','gstatic.com'],
        'facebook':['facebook.com','fb.com','meta.com'],
        'microsoft':['microsoft.com','live.com','outlook.com','microsoftonline.com','office.com'],
        'apple':['apple.com','icloud.com'],'icloud':['apple.com','icloud.com'],
        'amazon':['amazon.com','amazon.co.uk','amazon.in','amazon.de'],
        'instagram':['instagram.com','facebook.com','meta.com'],
        'linkedin':['linkedin.com'],'netflix':['netflix.com'],
        'twitter':['twitter.com','x.com'],'whatsapp':['whatsapp.com'],
        'spotify':['spotify.com'],'dropbox':['dropbox.com'],'github':['github.com'],
        'steam':['steampowered.com','steamcommunity.com'],
        'discord':['discord.com','discordapp.com'],'ebay':['ebay.com'],
        'yahoo':['yahoo.com'],'adobe':['adobe.com'],'reddit':['reddit.com'],
        'roblox':['roblox.com'],'zelle':['zelle.com','zellepay.com'],
        'coinbase':['coinbase.com'],'binance':['binance.com'],
        'chase':['chase.com'],'wellsfargo':['wellsfargo.com'],
    }

    title_patterns = ['{} - log in','{} - sign in','{} – log in','{} – sign in',
        'log in to {}','sign in to {}','login to {}','welcome to {}',
        '{} login','{} sign in','{} - sign up','{} account',
        'sign in - {}','log in - {}','connecter avec {}','identifiant {}']

    for brand, doms in brands.items():
        title_is = (page_title == brand or page_title.startswith(brand+' ') or
                    page_title.startswith(brand+'-') or page_title.startswith(brand+'–'))
        title_match = any(p.format(brand) in page_title for p in title_patterns)
        if (title_is or title_match) and not any(d in current_domain for d in doms):
            score += 25
            findings.append(f"Brand impersonation: title='{brand}' domain='{current_domain}'")
            break

    for brand, doms in brands.items():
        if brand in hostname and len(brand) > 3 and not any(d in current_domain for d in doms):
            score += 20
            findings.append(f"Brand in hostname: '{brand}' in '{hostname}'")
            break

    for brand, doms in brands.items():
        pattern = rf'{re.escape(brand)}\.com\.[a-z]{{2,3}}$'
        if re.search(pattern, hostname):
            if not any(d in current_domain for d in doms):
                score += 40
                findings.append(f"Fake domain pattern: {brand}.com.xx ({hostname})")
                break

    url_lower = url.lower()
    typos = {'google':['googel','gooogle','g00gle'],'facebook':['faceboook','facebok','faceb00k'],
             'paypal':['paypai','paypa1','paypol'],'microsoft':['microsft','mircosoft','micros0ft'],
             'apple':['appie','app1e','appl3'],'amazon':['amaz0n','amazn','arnazon'],
             'roblox':['robiox','r0blox','roblx','rob1ox'],
             'coinbase':['coinbas3','c0inbase','coinbse']}
    for brand, variants in typos.items():
        for v in variants:
            if v in url_lower or v in page_text:
                score += 25
                findings.append(f"Misspelling: '{v}'")
                break
        if score >= 20:
            break

    all_text = page_title + " " + page_text
    urgency = ['immediately','urgent','suspended','blocked','locked','unauthorized',
               'unusual activity','act now','within 24 hours','within 48 hours',
               'account will be closed','permanently','failure to','security alert']
    found_u = [w for w in urgency if w in all_text]
    if len(found_u) >= 4:
        score += 15; findings.append(f"{len(found_u)} urgency keywords")
    elif len(found_u) >= 2:
        score += 5; findings.append(f"{len(found_u)} urgency keywords")

    sensitive = ['social security','ssn','credit card number','credit card','card number',
                 'cvv','cvc','bank account number','routing number','pin number',
                 'mother maiden name','passport number']
    found_s = [s for s in sensitive if s in all_text]
    if len(found_s) >= 2:
        score += 15; findings.append(f"Sensitive data: {', '.join(found_s[:3])}")
    elif len(found_s) == 1:
        score += 10; findings.append(f"Sensitive data: {found_s[0]}")

    for w in ['clone','replica','phishing','fake','scam']:
        if w in url_lower or w in page_title:
            score += 15; findings.append(f"Keyword '{w}' in URL/title"); break

    sale_keywords = ['this domain is for sale', 'buy this domain', 'domain for sale',
                     'make an offer', 'domain name for sale', 'parked domain',
                     'this page is parked', 'domain parking']
    found_sale = [s for s in sale_keywords if s in all_text]
    if found_sale:
        score += 10; findings.append("Domain for sale page")

    return min(score, 100), findings


# Engine 2 Detection Function

def engine2_detect(driver, url):
    t0 = time.time()

    try:
        final_url = driver.current_url
    except Exception:
        final_url = url

    features = extract_all_features(driver, final_url)
    X_input = e2_scaler.transform(features_to_array(features))
    ml_proba = e2_ml_model.predict_proba(X_input)[0]
    ml_score = ml_proba[1] * 100

    nlp_score, nlp_findings = nlp_analysis(driver, final_url)

    final_hostname = (urlparse(final_url).hostname or "").lower()
    is_hosting = any(final_hostname.endswith(h) for h in UNTRUSTED_HOSTING)
    is_forsale = any(h in final_url.lower() for h in FORSALE_INDICATORS)

    is_trusted = False
    if not is_hosting and not is_forsale:
        is_trusted = e2_is_tranco_domain(url) or e2_is_tranco_domain(final_url)

    if nlp_score >= 25:
        combined = (0.40 * ml_score) + (0.60 * nlp_score)
        if is_trusted and nlp_score < 40:
            verdict = "LEGITIMATE"
        else:
            verdict = "PHISHING" if combined > 35 else "LEGITIMATE"
        method = "NLP-led"

    elif nlp_score > 0 and ml_score > 60:
        combined = (0.50 * ml_score) + (0.50 * nlp_score)
        if is_trusted:
            verdict = "LEGITIMATE"
        else:
            verdict = "PHISHING" if combined > 50 else "LEGITIMATE"
        method = "balanced"

    elif is_trusted:
        combined = ml_score * 0.3
        verdict = "LEGITIMATE"
        method = "Tranco-verified"

    elif is_hosting:
        combined = ml_score
        verdict = "PHISHING" if combined > 60 else "LEGITIMATE"
        method = "ML-hosting"

    elif is_forsale:
        combined = ml_score
        verdict = "PHISHING" if combined > 50 else "LEGITIMATE"
        method = "ML-forsale"

    else:
        combined = ml_score
        verdict = "PHISHING" if combined > 75 else "LEGITIMATE"
        method = "ML-only"

    combined = max(0, min(combined, 100))
    elapsed = time.time() - t0

    if verdict == "PHISHING":
        confidence = combined
    else:
        confidence = 100 - combined

    return verdict, confidence, {
        'ml_score': ml_score,
        'nlp_score': nlp_score,
        'nlp_findings': nlp_findings,
        'is_trusted': is_trusted,
        'is_hosting': is_hosting,
        'is_forsale': is_forsale,
        'method': method,
        'confidence': confidence,
        'combined_score': combined,
        'final_url': final_url,
        'elapsed_s': elapsed,
    }

# ════════════════════════════════════════════════════════════════
# CELL 5 — Engine 3: Screenshot CNN (EfficientNet-B0) (SERVER)
# ════════════════════════════════════════════════════════════════

# Model Architecture

class PhishDetector(nn.Module):
    def __init__(self):
        super().__init__()
        self.net = EfficientNet.from_name('efficientnet-b0')
        for p in list(self.net.parameters())[:-30]:
            p.requires_grad = False
        inf = self.net._fc.in_features
        self.net._fc = nn.Sequential(
            nn.Dropout(0.4),
            nn.Linear(inf, 512),
            nn.ReLU(),
            nn.BatchNorm1d(512),
            nn.Dropout(0.2),
            nn.Linear(512, 2)
        )
    def forward(self, x):
        return self.net(x)


# Load Trained Weights

e3_checkpoint = torch.load(E3_CNN_WEIGHTS, map_location=DEVICE, weights_only=False)

e3_model = PhishDetector().to(DEVICE)
e3_model.load_state_dict(e3_checkpoint['model_state_dict'])
e3_model.eval()

E3_CLASSES   = e3_checkpoint.get('class_names', ['legitimate', 'phishing'])
E3_IMG_SIZE  = e3_checkpoint.get('img_size', 224)


# Image Transform

_e3_normalize_mean = e3_checkpoint.get('normalize_mean', [0.485, 0.456, 0.406])
_e3_normalize_std  = e3_checkpoint.get('normalize_std', [0.229, 0.224, 0.225])

e3_eval_transform = transforms.Compose([
    transforms.Resize((E3_IMG_SIZE, E3_IMG_SIZE)),
    transforms.ToTensor(),
    transforms.Normalize(_e3_normalize_mean, _e3_normalize_std)
])


# Screenshot Capture

def capture_screenshot(driver, save_path=SCREENSHOT_PATH):
    try:
        try:
            driver.execute_script("""
                var buttons = document.querySelectorAll('button, a, div[role="button"]');
                for(var b of buttons){
                    var t = b.innerText.toLowerCase();
                    if(t.includes('accept') || t.includes('agree') || t.includes('allow')
                       || t.includes('consent') || t.includes('ok') || t.includes('got it')){
                        b.click(); break;
                    }
                }
            """)
            time.sleep(1)
        except Exception:
            pass

        driver.save_screenshot(save_path)

        if not os.path.exists(save_path):
            return False, ""
        if os.path.getsize(save_path) < 1000:
            return False, ""

        return True, save_path

    except Exception:
        return False, ""


# Engine 3 Detection Function

def engine3_detect(screenshot_path):
    t0 = time.time()

    try:
        img = Image.open(screenshot_path).convert('RGB')
        tensor = e3_eval_transform(img).unsqueeze(0).to(DEVICE)

        e3_model.eval()
        with torch.no_grad():
            output = e3_model(tensor)
            prob = torch.nn.functional.softmax(output, dim=1)
            conf_val, pred_idx = torch.max(prob, 1)

        result = E3_CLASSES[pred_idx.item()]
        confidence = conf_val.item() * 100
        legit_prob = prob[0][0].item() * 100
        phish_prob = prob[0][1].item() * 100

        verdict = "PHISHING" if result == "phishing" else "LEGITIMATE"
        elapsed = time.time() - t0

        return verdict, confidence, {
            'prediction': result,
            'confidence': confidence,
            'legit_prob': legit_prob,
            'phish_prob': phish_prob,
            'elapsed_s': elapsed,
        }

    except Exception as e:
        return "LEGITIMATE", 50.0, {
            'prediction': 'error',
            'confidence': 50.0,
            'legit_prob': 50.0,
            'phish_prob': 50.0,
            'elapsed_s': time.time() - t0,
            'error': str(e),
        }

# ════════════════════════════════════════════════════════════════
# CELL 6 — Master Pipeline (SERVER)
# scan_url() — Colab wali debug version nahi chahiye server pe
# pipeline_scan() — Cell 7 mein aayega (clean API version)
# Ye cell sirf browser helper rakhta hai
# ════════════════════════════════════════════════════════════════

# Browser Helper

def _open_url_in_browser(url):
    driver = None
    try:
        driver = create_driver()
        driver.set_page_load_timeout(PAGE_LOAD_TIMEOUT)
        driver.get(url)

        try:
            WebDriverWait(driver, PAGE_WAIT_TIMEOUT).until(
                lambda d: d.execute_script("return document.readyState") == "complete"
            )
        except TimeoutException:
            pass

        time.sleep(EXTRA_RENDER_WAIT)
        final_url = driver.current_url
        return driver, final_url, None

    except InvalidArgumentException:
        if driver:
            try: driver.quit()
            except: pass
        return None, url, "Invalid URL format"

    except TimeoutException:
        if driver:
            try: driver.quit()
            except: pass
        return None, url, "Page load timeout"

    except WebDriverException as e:
        if driver:
            try: driver.quit()
            except: pass
        msg = str(e.msg)[:80] if hasattr(e, 'msg') and e.msg else str(e)[:80]
        return None, url, f"Browser error: {msg}"

    except Exception as e:
        if driver:
            try: driver.quit()
            except: pass
        return None, url, f"{type(e).__name__}: {str(e)[:60]}"

# ════════════════════════════════════════════════════════════════
# CELL 7 — pipeline_scan() (SERVER)
# Main detection function — Flask API isko call karega
# Returns: (verdict, confidence, engines_used)
# ════════════════════════════════════════════════════════════════

def pipeline_scan(url):
    t0 = time.time()
    driver = None

    # ── Stage 1: Engine 1 (no browser) ──────────────────────────
    e1_result = predictor.predict(url)
    e1_route   = e1_result['decision_path']
    e1_conf    = e1_result['confidence']
    e1_phish   = e1_result['is_phish']

    # E1 PHISHING → EXIT
    if e1_phish:
        verdict    = "PHISHING"
        confidence = e1_conf * 100
        record_scan(url, verdict, "E1")
        return verdict, confidence, "E1"

    # E1 LEGITIMATE → proceed to E2
    # ── Stage 2: Engine 2 (browser required) ────────────────────
    browser_url = url if url.startswith(('http://', 'https://')) else 'https://' + url

    try:
        driver = create_driver()
        driver.set_page_load_timeout(25)
        driver.get(browser_url)
        try:
            WebDriverWait(driver, 15).until(
                lambda d: d.execute_script("return document.readyState") == "complete"
            )
        except TimeoutException:
            pass
        time.sleep(1.5)
        final_url = driver.current_url

    except Exception:
        if driver:
            try: driver.quit()
            except: pass
        record_scan(url, "LINK DOES NOT EXIST", "ERROR")
        return "LINK DOES NOT EXIST", 0, "ERROR"

    # ML prediction
    features = {**extract_url_features(final_url), **extract_html_features(driver)}
    X_input  = e2_scaler.transform(features_to_array(features))
    ml_proba = e2_ml_model.predict_proba(X_input)[0]
    ml_score = ml_proba[1] * 100

    # NLP analysis
    nlp_score, nlp_findings = nlp_analysis(driver, final_url)

    # Tranco / hosting check
    final_hostname = (urlparse(final_url).hostname or "").lower()
    is_hosting = any(final_hostname.endswith(h) for h in UNTRUSTED_HOSTING)
    is_trusted = False
    if not is_hosting:
        is_trusted = e2_is_tranco_domain(url) or e2_is_tranco_domain(final_url)

    # E2 decision logic
    if nlp_score >= 25:
        combined   = (0.40 * ml_score) + (0.60 * nlp_score)
        if is_trusted and nlp_score < 40:
            e2_verdict = "LEGITIMATE"
        else:
            e2_verdict = "PHISHING" if combined > 35 else "LEGITIMATE"
    elif nlp_score > 0 and ml_score > 60:
        combined   = (0.50 * ml_score) + (0.50 * nlp_score)
        if is_trusted:
            e2_verdict = "LEGITIMATE"
        else:
            e2_verdict = "PHISHING" if combined > 50 else "LEGITIMATE"
    elif is_trusted:
        combined   = ml_score * 0.3
        e2_verdict = "LEGITIMATE"
    elif is_hosting:
        combined   = ml_score
        e2_verdict = "PHISHING" if combined > 60 else "LEGITIMATE"
    else:
        combined   = ml_score
        e2_verdict = "PHISHING" if combined > 75 else "LEGITIMATE"

    combined = max(0, min(combined, 100))
    e2_confidence = combined if e2_verdict == "PHISHING" else 100 - combined

    # E2 PHISHING → EXIT
    if e2_verdict == "PHISHING":
        try: driver.quit()
        except: pass
        record_scan(url, "PHISHING", "E1->E2")
        return "PHISHING", e2_confidence, "E1->E2"

    # E2 LEGITIMATE with confidence >= 55% → EXIT
    if e2_verdict == "LEGITIMATE" and e2_confidence >= 55:
        try: driver.quit()
        except: pass
        record_scan(url, "LEGITIMATE", "E1->E2")
        return "LEGITIMATE", e2_confidence, "E1->E2"

    # E2 uncertain (< 55%) → Engine 3
    # ── Stage 3: Engine 3 (same browser session) ─────────────────
    shot_path = "/tmp/pipeline_shot.png"

    # Dismiss popups
    try:
        driver.execute_script("""
            var buttons = document.querySelectorAll('button, a, div[role="button"]');
            for(var b of buttons){
                var t = b.innerText.toLowerCase();
                if(t.includes('accept')||t.includes('agree')||t.includes('allow')
                   ||t.includes('consent')||t.includes('ok')||t.includes('got it')){
                    b.click(); break;
                }
            }
        """)
        time.sleep(1)
    except Exception:
        pass

    driver.save_screenshot(shot_path)
    try: driver.quit()
    except: pass

    # Screenshot fallback
    if not os.path.exists(shot_path) or os.path.getsize(shot_path) < 1000:
        record_scan(url, e2_verdict, "E1->E2-fallback")
        return e2_verdict, e2_confidence, "E1->E2-fallback"

    # CNN prediction
    img    = Image.open(shot_path).convert('RGB')
    tensor = e3_eval_transform(img).unsqueeze(0).to(DEVICE)
    e3_model.eval()
    with torch.no_grad():
        output = e3_model(tensor)
        prob   = torch.nn.functional.softmax(output, dim=1)
    phish_prob = prob[0][1].item() * 100

    # Final: E2 x 50% + E3 x 50%
    final_phish = (0.50 * combined) + (0.50 * phish_prob)

    if final_phish >= 50:
        verdict    = "PHISHING"
        confidence = final_phish
    else:
        verdict    = "LEGITIMATE"
        confidence = 100 - final_phish

    record_scan(url, verdict, "E1->E2->E3")
    return verdict, confidence, "E1->E2->E3"

# ════════════════════════════════════════════════════════════════
# CELL 8 — Flask Web Server + API (SERVER)
# Widgets ki jagah → REST API + HTML Frontend
# ════════════════════════════════════════════════════════════════

from flask import Flask, request, jsonify, send_from_directory
from flask_cors import CORS

app = Flask(__name__, static_folder=WEBSITE_DIR)
CORS(app)

# Initialize stats database on startup
init_stats_db()


# ── API Endpoint ─────────────────────────────────────────────

@app.route('/api/scan', methods=['POST'])
def api_scan():
    data = request.get_json(force=True, silent=True) or {}
    url = (data.get('url') or '').strip()

    if not url:
        return jsonify({'error': 'URL is required'}), 400

    try:
        verdict, confidence, engines = pipeline_scan(url)
        return jsonify({
            'url': url,
            'verdict': verdict,
            'confidence': round(confidence, 1),
            'engines': engines,
        })
    except Exception as e:
        return jsonify({
            'url': url,
            'verdict': 'ERROR',
            'confidence': 0,
            'engines': '',
            'error': str(e)[:200],
        }), 500


# ── Health Check ─────────────────────────────────────────────

@app.route('/api/health', methods=['GET'])
def health():
    return jsonify({'status': 'ok', 'engine_version': ENGINE_VERSION})


# ── Stats Endpoint (NEW) ────────────────────────────────────

@app.route('/api/stats', methods=['GET'])
def api_stats():
    """Returns shared stats for ALL users."""
    increment_visitors()
    stats = get_stats()
    return jsonify(stats)


# ── Recent Scans Endpoint (NEW) ─────────────────────────────

@app.route('/api/recent', methods=['GET'])
def api_recent():
    """Returns last 10 scans for ALL users."""
    scans = get_recent_scans(10)
    return jsonify(scans)


# ── Serve Frontend ───────────────────────────────────────────

@app.route('/')
def index():
    return send_from_directory(WEBSITE_DIR, 'index.html')

@app.route('/<path:filename>')
def static_files(filename):
    return send_from_directory(WEBSITE_DIR, filename)


# ── Run Server ───────────────────────────────────────────────

if __name__ == '__main__':
    app.run(host='127.0.0.1', port=5000, debug=False)